// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpcMap.proto

package rpcmapclient

import (
	"context"

	"rpcMap/rpcMap"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetCoordinatesReq  = rpcMap.GetCoordinatesReq
	GetCoordinatesResp = rpcMap.GetCoordinatesResp
	IssueCouponsReq    = rpcMap.IssueCouponsReq
	IssueCouponsResp   = rpcMap.IssueCouponsResp
	MapChatReq         = rpcMap.MapChatReq
	MapChatResp        = rpcMap.MapChatResp
	MapRpcTestReq      = rpcMap.MapRpcTestReq
	MapRpcTestResp     = rpcMap.MapRpcTestResp
	Request            = rpcMap.Request
	Response           = rpcMap.Response
	ReverseGeocodeReq  = rpcMap.ReverseGeocodeReq
	ReverseGeocodeResp = rpcMap.ReverseGeocodeResp

	RpcMap interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		MapRpcTest(ctx context.Context, in *MapRpcTestReq, opts ...grpc.CallOption) (*MapRpcTestResp, error)
		GetCoordinates(ctx context.Context, in *GetCoordinatesReq, opts ...grpc.CallOption) (*GetCoordinatesResp, error)
		ReverseGeocode(ctx context.Context, in *ReverseGeocodeReq, opts ...grpc.CallOption) (*ReverseGeocodeResp, error)
		IssueCoupons(ctx context.Context, in *IssueCouponsReq, opts ...grpc.CallOption) (*IssueCouponsResp, error)
		MapChat(ctx context.Context, in *MapChatReq, opts ...grpc.CallOption) (*MapChatResp, error)
	}

	defaultRpcMap struct {
		cli zrpc.Client
	}
)

func NewRpcMap(cli zrpc.Client) RpcMap {
	return &defaultRpcMap{
		cli: cli,
	}
}

func (m *defaultRpcMap) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpcMap.NewRpcMapClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultRpcMap) MapRpcTest(ctx context.Context, in *MapRpcTestReq, opts ...grpc.CallOption) (*MapRpcTestResp, error) {
	client := rpcMap.NewRpcMapClient(m.cli.Conn())
	return client.MapRpcTest(ctx, in, opts...)
}

func (m *defaultRpcMap) GetCoordinates(ctx context.Context, in *GetCoordinatesReq, opts ...grpc.CallOption) (*GetCoordinatesResp, error) {
	client := rpcMap.NewRpcMapClient(m.cli.Conn())
	return client.GetCoordinates(ctx, in, opts...)
}

func (m *defaultRpcMap) ReverseGeocode(ctx context.Context, in *ReverseGeocodeReq, opts ...grpc.CallOption) (*ReverseGeocodeResp, error) {
	client := rpcMap.NewRpcMapClient(m.cli.Conn())
	return client.ReverseGeocode(ctx, in, opts...)
}

func (m *defaultRpcMap) IssueCoupons(ctx context.Context, in *IssueCouponsReq, opts ...grpc.CallOption) (*IssueCouponsResp, error) {
	client := rpcMap.NewRpcMapClient(m.cli.Conn())
	return client.IssueCoupons(ctx, in, opts...)
}

func (m *defaultRpcMap) MapChat(ctx context.Context, in *MapChatReq, opts ...grpc.CallOption) (*MapChatResp, error) {
	client := rpcMap.NewRpcMapClient(m.cli.Conn())
	return client.MapChat(ctx, in, opts...)
}
