// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpcOrder.proto

package server

import (
	"context"

	"rpcOrder/internal/logic"
	"rpcOrder/internal/svc"
	"rpcOrder/rpcOrder"
)

type RpcOrderServer struct {
	svcCtx *svc.ServiceContext
	rpcOrder.UnimplementedRpcOrderServer
}

func NewRpcOrderServer(svcCtx *svc.ServiceContext) *RpcOrderServer {
	return &RpcOrderServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcOrderServer) Ping(ctx context.Context, in *rpcOrder.Request) (*rpcOrder.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *RpcOrderServer) OrderRpcTest(ctx context.Context, in *rpcOrder.OrderRpcTestReq) (*rpcOrder.OrderRpcTestResp, error) {
	l := logic.NewOrderRpcTestLogic(ctx, s.svcCtx)
	return l.OrderRpcTest(in)
}

func (s *RpcOrderServer) Journey(ctx context.Context, in *rpcOrder.JourneyReq) (*rpcOrder.JourneyResp, error) {
	l := logic.NewJourneyLogic(ctx, s.svcCtx)
	return l.Journey(in)
}

func (s *RpcOrderServer) TakeCar(ctx context.Context, in *rpcOrder.TakeCarReq) (*rpcOrder.TakeCarResp, error) {
	l := logic.NewTakeCarLogic(ctx, s.svcCtx)
	return l.TakeCar(in)
}

func (s *RpcOrderServer) GrabList(ctx context.Context, in *rpcOrder.GrabListReq) (*rpcOrder.GrabListResp, error) {
	l := logic.NewGrabListLogic(ctx, s.svcCtx)
	return l.GrabList(in)
}

func (s *RpcOrderServer) GrabOrder(ctx context.Context, in *rpcOrder.GrabOrderReq) (*rpcOrder.GrabOrderResp, error) {
	l := logic.NewGrabOrderLogic(ctx, s.svcCtx)
	return l.GrabOrder(in)
}

func (s *RpcOrderServer) OrderOver(ctx context.Context, in *rpcOrder.OrderOverReq) (*rpcOrder.OrderOverResp, error) {
	l := logic.NewOrderOverLogic(ctx, s.svcCtx)
	return l.OrderOver(in)
}

func (s *RpcOrderServer) StartOrder(ctx context.Context, in *rpcOrder.StartOrderReq) (*rpcOrder.StartOrderResp, error) {
	l := logic.NewStartOrderLogic(ctx, s.svcCtx)
	return l.StartOrder(in)
}

func (s *RpcOrderServer) CancelOrder(ctx context.Context, in *rpcOrder.CancelOrderReq) (*rpcOrder.CancelOrderResp, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

func (s *RpcOrderServer) DriverOngoing(ctx context.Context, in *rpcOrder.DriverOngoingReq) (*rpcOrder.DriverOngoingResp, error) {
	l := logic.NewDriverOngoingLogic(ctx, s.svcCtx)
	return l.DriverOngoing(in)
}

func (s *RpcOrderServer) UserOngoing(ctx context.Context, in *rpcOrder.UserOngoingReq) (*rpcOrder.UserOngoingResp, error) {
	l := logic.NewUserOngoingLogic(ctx, s.svcCtx)
	return l.UserOngoing(in)
}
