// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpcOrder.proto

package rpcorderclient

import (
	"context"

	"rpcOrder/rpcOrder"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderReq    = rpcOrder.CancelOrderReq
	CancelOrderResp   = rpcOrder.CancelOrderResp
	DriverOngoingReq  = rpcOrder.DriverOngoingReq
	DriverOngoingResp = rpcOrder.DriverOngoingResp
	GrabListReq       = rpcOrder.GrabListReq
	GrabListResp      = rpcOrder.GrabListResp
	GrabOrderItem     = rpcOrder.GrabOrderItem
	GrabOrderReq      = rpcOrder.GrabOrderReq
	GrabOrderResp     = rpcOrder.GrabOrderResp
	JourneyReq        = rpcOrder.JourneyReq
	JourneyResp       = rpcOrder.JourneyResp
	OrderOverReq      = rpcOrder.OrderOverReq
	OrderOverResp     = rpcOrder.OrderOverResp
	OrderRpcTestReq   = rpcOrder.OrderRpcTestReq
	OrderRpcTestResp  = rpcOrder.OrderRpcTestResp
	Request           = rpcOrder.Request
	Response          = rpcOrder.Response
	RoutePoint        = rpcOrder.RoutePoint
	StartOrderReq     = rpcOrder.StartOrderReq
	StartOrderResp    = rpcOrder.StartOrderResp
	TakeCarReq        = rpcOrder.TakeCarReq
	TakeCarResp       = rpcOrder.TakeCarResp
	UserOngoingItem   = rpcOrder.UserOngoingItem
	UserOngoingReq    = rpcOrder.UserOngoingReq
	UserOngoingResp   = rpcOrder.UserOngoingResp

	RpcOrder interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		OrderRpcTest(ctx context.Context, in *OrderRpcTestReq, opts ...grpc.CallOption) (*OrderRpcTestResp, error)
		Journey(ctx context.Context, in *JourneyReq, opts ...grpc.CallOption) (*JourneyResp, error)
		TakeCar(ctx context.Context, in *TakeCarReq, opts ...grpc.CallOption) (*TakeCarResp, error)
		GrabList(ctx context.Context, in *GrabListReq, opts ...grpc.CallOption) (*GrabListResp, error)
		GrabOrder(ctx context.Context, in *GrabOrderReq, opts ...grpc.CallOption) (*GrabOrderResp, error)
		OrderOver(ctx context.Context, in *OrderOverReq, opts ...grpc.CallOption) (*OrderOverResp, error)
		StartOrder(ctx context.Context, in *StartOrderReq, opts ...grpc.CallOption) (*StartOrderResp, error)
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
		DriverOngoing(ctx context.Context, in *DriverOngoingReq, opts ...grpc.CallOption) (*DriverOngoingResp, error)
		UserOngoing(ctx context.Context, in *UserOngoingReq, opts ...grpc.CallOption) (*UserOngoingResp, error)
	}

	defaultRpcOrder struct {
		cli zrpc.Client
	}
)

func NewRpcOrder(cli zrpc.Client) RpcOrder {
	return &defaultRpcOrder{
		cli: cli,
	}
}

func (m *defaultRpcOrder) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultRpcOrder) OrderRpcTest(ctx context.Context, in *OrderRpcTestReq, opts ...grpc.CallOption) (*OrderRpcTestResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.OrderRpcTest(ctx, in, opts...)
}

func (m *defaultRpcOrder) Journey(ctx context.Context, in *JourneyReq, opts ...grpc.CallOption) (*JourneyResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.Journey(ctx, in, opts...)
}

func (m *defaultRpcOrder) TakeCar(ctx context.Context, in *TakeCarReq, opts ...grpc.CallOption) (*TakeCarResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.TakeCar(ctx, in, opts...)
}

func (m *defaultRpcOrder) GrabList(ctx context.Context, in *GrabListReq, opts ...grpc.CallOption) (*GrabListResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.GrabList(ctx, in, opts...)
}

func (m *defaultRpcOrder) GrabOrder(ctx context.Context, in *GrabOrderReq, opts ...grpc.CallOption) (*GrabOrderResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.GrabOrder(ctx, in, opts...)
}

func (m *defaultRpcOrder) OrderOver(ctx context.Context, in *OrderOverReq, opts ...grpc.CallOption) (*OrderOverResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.OrderOver(ctx, in, opts...)
}

func (m *defaultRpcOrder) StartOrder(ctx context.Context, in *StartOrderReq, opts ...grpc.CallOption) (*StartOrderResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.StartOrder(ctx, in, opts...)
}

func (m *defaultRpcOrder) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

func (m *defaultRpcOrder) DriverOngoing(ctx context.Context, in *DriverOngoingReq, opts ...grpc.CallOption) (*DriverOngoingResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.DriverOngoing(ctx, in, opts...)
}

func (m *defaultRpcOrder) UserOngoing(ctx context.Context, in *UserOngoingReq, opts ...grpc.CallOption) (*UserOngoingResp, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.UserOngoing(ctx, in, opts...)
}
