// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpcOrder.proto

package rpcOrder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_rpcOrder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_rpcOrder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type OrderRpcTestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRpcTestReq) Reset() {
	*x = OrderRpcTestReq{}
	mi := &file_rpcOrder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRpcTestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRpcTestReq) ProtoMessage() {}

func (x *OrderRpcTestReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRpcTestReq.ProtoReflect.Descriptor instead.
func (*OrderRpcTestReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{2}
}

func (x *OrderRpcTestReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OrderRpcTestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRpcTestResp) Reset() {
	*x = OrderRpcTestResp{}
	mi := &file_rpcOrder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRpcTestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRpcTestResp) ProtoMessage() {}

func (x *OrderRpcTestResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRpcTestResp.ProtoReflect.Descriptor instead.
func (*OrderRpcTestResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{3}
}

func (x *OrderRpcTestResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type JourneyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartingPoint string                 `protobuf:"bytes,1,opt,name=startingPoint,proto3" json:"startingPoint,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JourneyReq) Reset() {
	*x = JourneyReq{}
	mi := &file_rpcOrder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyReq) ProtoMessage() {}

func (x *JourneyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyReq.ProtoReflect.Descriptor instead.
func (*JourneyReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{4}
}

func (x *JourneyReq) GetStartingPoint() string {
	if x != nil {
		return x.StartingPoint
	}
	return ""
}

func (x *JourneyReq) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *JourneyReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type RoutePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lng           float64                `protobuf:"fixed64,1,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePoint) Reset() {
	*x = RoutePoint{}
	mi := &file_rpcOrder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePoint) ProtoMessage() {}

func (x *RoutePoint) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePoint.ProtoReflect.Descriptor instead.
func (*RoutePoint) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{5}
}

func (x *RoutePoint) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *RoutePoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type JourneyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float32                `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Distance      int64                  `protobuf:"varint,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Waittine      int64                  `protobuf:"varint,5,opt,name=waittine,proto3" json:"waittine,omitempty"`
	StartAdcode   string                 `protobuf:"bytes,6,opt,name=start_adcode,json=startAdcode,proto3" json:"start_adcode,omitempty"`         // 起点行政区划代码，供前端筛券
	StartCityName string                 `protobuf:"bytes,7,opt,name=start_city_name,json=startCityName,proto3" json:"start_city_name,omitempty"` // 起点城市名
	StartLng      float64                `protobuf:"fixed64,8,opt,name=start_lng,json=startLng,proto3" json:"start_lng,omitempty"`
	StartLat      float64                `protobuf:"fixed64,9,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	EndLng        float64                `protobuf:"fixed64,10,opt,name=end_lng,json=endLng,proto3" json:"end_lng,omitempty"`
	EndLat        float64                `protobuf:"fixed64,11,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	RoutePoints   []*RoutePoint          `protobuf:"bytes,12,rep,name=route_points,json=routePoints,proto3" json:"route_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JourneyResp) Reset() {
	*x = JourneyResp{}
	mi := &file_rpcOrder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyResp) ProtoMessage() {}

func (x *JourneyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyResp.ProtoReflect.Descriptor instead.
func (*JourneyResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{6}
}

func (x *JourneyResp) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *JourneyResp) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *JourneyResp) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *JourneyResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *JourneyResp) GetWaittine() int64 {
	if x != nil {
		return x.Waittine
	}
	return 0
}

func (x *JourneyResp) GetStartAdcode() string {
	if x != nil {
		return x.StartAdcode
	}
	return ""
}

func (x *JourneyResp) GetStartCityName() string {
	if x != nil {
		return x.StartCityName
	}
	return ""
}

func (x *JourneyResp) GetStartLng() float64 {
	if x != nil {
		return x.StartLng
	}
	return 0
}

func (x *JourneyResp) GetStartLat() float64 {
	if x != nil {
		return x.StartLat
	}
	return 0
}

func (x *JourneyResp) GetEndLng() float64 {
	if x != nil {
		return x.EndLng
	}
	return 0
}

func (x *JourneyResp) GetEndLat() float64 {
	if x != nil {
		return x.EndLat
	}
	return 0
}

func (x *JourneyResp) GetRoutePoints() []*RoutePoint {
	if x != nil {
		return x.RoutePoints
	}
	return nil
}

type TakeCarReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartingPoint string                 `protobuf:"bytes,1,opt,name=startingPoint,proto3" json:"startingPoint,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Tid           int64                  `protobuf:"varint,4,opt,name=tid,proto3" json:"tid,omitempty"` // 优惠券id，0表示不使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeCarReq) Reset() {
	*x = TakeCarReq{}
	mi := &file_rpcOrder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeCarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeCarReq) ProtoMessage() {}

func (x *TakeCarReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeCarReq.ProtoReflect.Descriptor instead.
func (*TakeCarReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{7}
}

func (x *TakeCarReq) GetStartingPoint() string {
	if x != nil {
		return x.StartingPoint
	}
	return ""
}

func (x *TakeCarReq) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TakeCarReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TakeCarReq) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

type TakeCarResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`      // 路况
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`       // 优惠后实付金额
	Distance      float32                `protobuf:"fixed32,3,opt,name=distance,proto3" json:"distance,omitempty"` // 公里
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`  // 分钟
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	OrderNo       string                 `protobuf:"bytes,6,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeCarResp) Reset() {
	*x = TakeCarResp{}
	mi := &file_rpcOrder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeCarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeCarResp) ProtoMessage() {}

func (x *TakeCarResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeCarResp.ProtoReflect.Descriptor instead.
func (*TakeCarResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{8}
}

func (x *TakeCarResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TakeCarResp) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TakeCarResp) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TakeCarResp) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TakeCarResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TakeCarResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GrabListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	RadiusM       int64                  `protobuf:"varint,2,opt,name=radiusM,proto3" json:"radiusM,omitempty"` // 搜索半径(米)，默认5000
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`     // 返回条数，默认20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrabListReq) Reset() {
	*x = GrabListReq{}
	mi := &file_rpcOrder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrabListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrabListReq) ProtoMessage() {}

func (x *GrabListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrabListReq.ProtoReflect.Descriptor instead.
func (*GrabListReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{9}
}

func (x *GrabListReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *GrabListReq) GetRadiusM() int64 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

func (x *GrabListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GrabOrderItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderNo          string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	StartLng         float64                `protobuf:"fixed64,3,opt,name=startLng,proto3" json:"startLng,omitempty"`
	StartLat         float64                `protobuf:"fixed64,4,opt,name=startLat,proto3" json:"startLat,omitempty"`
	StartAddress     string                 `protobuf:"bytes,5,opt,name=startAddress,proto3" json:"startAddress,omitempty"`
	EndLng           float64                `protobuf:"fixed64,6,opt,name=endLng,proto3" json:"endLng,omitempty"`
	EndLat           float64                `protobuf:"fixed64,7,opt,name=endLat,proto3" json:"endLat,omitempty"`
	EndAddress       string                 `protobuf:"bytes,8,opt,name=endAddress,proto3" json:"endAddress,omitempty"`
	Distance         float64                `protobuf:"fixed64,9,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration         int64                  `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`
	Price            float64                `protobuf:"fixed64,11,opt,name=price,proto3" json:"price,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,12,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	DistanceToDriver float64                `protobuf:"fixed64,13,opt,name=distanceToDriver,proto3" json:"distanceToDriver,omitempty"`
	Status           int64                  `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"` // 2已接单 5用户已上车
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GrabOrderItem) Reset() {
	*x = GrabOrderItem{}
	mi := &file_rpcOrder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrabOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrabOrderItem) ProtoMessage() {}

func (x *GrabOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrabOrderItem.ProtoReflect.Descriptor instead.
func (*GrabOrderItem) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{10}
}

func (x *GrabOrderItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GrabOrderItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GrabOrderItem) GetStartLng() float64 {
	if x != nil {
		return x.StartLng
	}
	return 0
}

func (x *GrabOrderItem) GetStartLat() float64 {
	if x != nil {
		return x.StartLat
	}
	return 0
}

func (x *GrabOrderItem) GetStartAddress() string {
	if x != nil {
		return x.StartAddress
	}
	return ""
}

func (x *GrabOrderItem) GetEndLng() float64 {
	if x != nil {
		return x.EndLng
	}
	return 0
}

func (x *GrabOrderItem) GetEndLat() float64 {
	if x != nil {
		return x.EndLat
	}
	return 0
}

func (x *GrabOrderItem) GetEndAddress() string {
	if x != nil {
		return x.EndAddress
	}
	return ""
}

func (x *GrabOrderItem) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *GrabOrderItem) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *GrabOrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GrabOrderItem) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GrabOrderItem) GetDistanceToDriver() float64 {
	if x != nil {
		return x.DistanceToDriver
	}
	return 0
}

func (x *GrabOrderItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GrabListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*GrabOrderItem       `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrabListResp) Reset() {
	*x = GrabListResp{}
	mi := &file_rpcOrder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrabListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrabListResp) ProtoMessage() {}

func (x *GrabListResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrabListResp.ProtoReflect.Descriptor instead.
func (*GrabListResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{11}
}

func (x *GrabListResp) GetOrders() []*GrabOrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GrabOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrabOrderReq) Reset() {
	*x = GrabOrderReq{}
	mi := &file_rpcOrder_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrabOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrabOrderReq) ProtoMessage() {}

func (x *GrabOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrabOrderReq.ProtoReflect.Descriptor instead.
func (*GrabOrderReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{12}
}

func (x *GrabOrderReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *GrabOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GrabOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0成功 1已被抢 2司机忙 3过期 5系统错
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrabOrderResp) Reset() {
	*x = GrabOrderResp{}
	mi := &file_rpcOrder_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrabOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrabOrderResp) ProtoMessage() {}

func (x *GrabOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrabOrderResp.ProtoReflect.Descriptor instead.
func (*GrabOrderResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{13}
}

func (x *GrabOrderResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GrabOrderResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GrabOrderResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type OrderOverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderOverReq) Reset() {
	*x = OrderOverReq{}
	mi := &file_rpcOrder_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderOverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderOverReq) ProtoMessage() {}

func (x *OrderOverReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderOverReq.ProtoReflect.Descriptor instead.
func (*OrderOverReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{14}
}

func (x *OrderOverReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *OrderOverReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type OrderOverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderOverResp) Reset() {
	*x = OrderOverResp{}
	mi := &file_rpcOrder_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderOverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderOverResp) ProtoMessage() {}

func (x *OrderOverResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderOverResp.ProtoReflect.Descriptor instead.
func (*OrderOverResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{15}
}

func (x *OrderOverResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StartOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	PhoneTail     string                 `protobuf:"bytes,3,opt,name=phoneTail,proto3" json:"phoneTail,omitempty"` // 乘客手机号后四位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrderReq) Reset() {
	*x = StartOrderReq{}
	mi := &file_rpcOrder_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderReq) ProtoMessage() {}

func (x *StartOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderReq.ProtoReflect.Descriptor instead.
func (*StartOrderReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{16}
}

func (x *StartOrderReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *StartOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *StartOrderReq) GetPhoneTail() string {
	if x != nil {
		return x.PhoneTail
	}
	return ""
}

type StartOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrderResp) Reset() {
	*x = StartOrderResp{}
	mi := &file_rpcOrder_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderResp) ProtoMessage() {}

func (x *StartOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderResp.ProtoReflect.Descriptor instead.
func (*StartOrderResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{17}
}

func (x *StartOrderResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartOrderResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // 取消原因，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_rpcOrder_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{18}
}

func (x *CancelOrderReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CancelOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CancelOrderReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResp) Reset() {
	*x = CancelOrderResp{}
	mi := &file_rpcOrder_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResp) ProtoMessage() {}

func (x *CancelOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResp.ProtoReflect.Descriptor instead.
func (*CancelOrderResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{19}
}

func (x *CancelOrderResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DriverOngoingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverOngoingReq) Reset() {
	*x = DriverOngoingReq{}
	mi := &file_rpcOrder_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverOngoingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverOngoingReq) ProtoMessage() {}

func (x *DriverOngoingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverOngoingReq.ProtoReflect.Descriptor instead.
func (*DriverOngoingReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{20}
}

func (x *DriverOngoingReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type DriverOngoingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasOrder      bool                   `protobuf:"varint,1,opt,name=hasOrder,proto3" json:"hasOrder,omitempty"`
	Order         *GrabOrderItem         `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverOngoingResp) Reset() {
	*x = DriverOngoingResp{}
	mi := &file_rpcOrder_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverOngoingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverOngoingResp) ProtoMessage() {}

func (x *DriverOngoingResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverOngoingResp.ProtoReflect.Descriptor instead.
func (*DriverOngoingResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{21}
}

func (x *DriverOngoingResp) GetHasOrder() bool {
	if x != nil {
		return x.HasOrder
	}
	return false
}

func (x *DriverOngoingResp) GetOrder() *GrabOrderItem {
	if x != nil {
		return x.Order
	}
	return nil
}

type UserOngoingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 1待接单 2已接单 5用户已上车
	StartAddress  string                 `protobuf:"bytes,3,opt,name=startAddress,proto3" json:"startAddress,omitempty"`
	EndAddress    string                 `protobuf:"bytes,4,opt,name=endAddress,proto3" json:"endAddress,omitempty"`
	Distance      float64                `protobuf:"fixed64,5,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      int64                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	DriverId      int64                  `protobuf:"varint,8,opt,name=driverId,proto3" json:"driverId,omitempty"`
	DriverName    string                 `protobuf:"bytes,9,opt,name=driverName,proto3" json:"driverName,omitempty"`
	CarNumber     string                 `protobuf:"bytes,10,opt,name=carNumber,proto3" json:"carNumber,omitempty"`
	CarType       string                 `protobuf:"bytes,11,opt,name=carType,proto3" json:"carType,omitempty"`
	DriverRating  float64                `protobuf:"fixed64,12,opt,name=driverRating,proto3" json:"driverRating,omitempty"`
	AcceptAt      int64                  `protobuf:"varint,13,opt,name=acceptAt,proto3" json:"acceptAt,omitempty"` // 接单时间 unix 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOngoingItem) Reset() {
	*x = UserOngoingItem{}
	mi := &file_rpcOrder_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOngoingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOngoingItem) ProtoMessage() {}

func (x *UserOngoingItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOngoingItem.ProtoReflect.Descriptor instead.
func (*UserOngoingItem) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{22}
}

func (x *UserOngoingItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *UserOngoingItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserOngoingItem) GetStartAddress() string {
	if x != nil {
		return x.StartAddress
	}
	return ""
}

func (x *UserOngoingItem) GetEndAddress() string {
	if x != nil {
		return x.EndAddress
	}
	return ""
}

func (x *UserOngoingItem) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *UserOngoingItem) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UserOngoingItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UserOngoingItem) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *UserOngoingItem) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *UserOngoingItem) GetCarNumber() string {
	if x != nil {
		return x.CarNumber
	}
	return ""
}

func (x *UserOngoingItem) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *UserOngoingItem) GetDriverRating() float64 {
	if x != nil {
		return x.DriverRating
	}
	return 0
}

func (x *UserOngoingItem) GetAcceptAt() int64 {
	if x != nil {
		return x.AcceptAt
	}
	return 0
}

type UserOngoingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOngoingReq) Reset() {
	*x = UserOngoingReq{}
	mi := &file_rpcOrder_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOngoingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOngoingReq) ProtoMessage() {}

func (x *UserOngoingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOngoingReq.ProtoReflect.Descriptor instead.
func (*UserOngoingReq) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{23}
}

func (x *UserOngoingReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserOngoingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasOrder      bool                   `protobuf:"varint,1,opt,name=hasOrder,proto3" json:"hasOrder,omitempty"`
	Order         *UserOngoingItem       `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOngoingResp) Reset() {
	*x = UserOngoingResp{}
	mi := &file_rpcOrder_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOngoingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOngoingResp) ProtoMessage() {}

func (x *UserOngoingResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcOrder_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOngoingResp.ProtoReflect.Descriptor instead.
func (*UserOngoingResp) Descriptor() ([]byte, []int) {
	return file_rpcOrder_proto_rawDescGZIP(), []int{24}
}

func (x *UserOngoingResp) GetHasOrder() bool {
	if x != nil {
		return x.HasOrder
	}
	return false
}

func (x *UserOngoingResp) GetOrder() *UserOngoingItem {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_rpcOrder_proto protoreflect.FileDescriptor

const file_rpcOrder_proto_rawDesc = "" +
	"\n" +
	"\x0erpcOrder.proto\x12\brpcOrder\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"#\n" +
	"\x0fOrderRpcTestReq\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"*\n" +
	"\x10OrderRpcTestResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"f\n" +
	"\n" +
	"JourneyReq\x12$\n" +
	"\rstartingPoint\x18\x01 \x01(\tR\rstartingPoint\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\"0\n" +
	"\n" +
	"RoutePoint\x12\x10\n" +
	"\x03lng\x18\x01 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\"\xff\x02\n" +
	"\vJourneyResp\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x02R\x05price\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x03R\bdistance\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x03R\bduration\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x1a\n" +
	"\bwaittine\x18\x05 \x01(\x03R\bwaittine\x12!\n" +
	"\fstart_adcode\x18\x06 \x01(\tR\vstartAdcode\x12&\n" +
	"\x0fstart_city_name\x18\a \x01(\tR\rstartCityName\x12\x1b\n" +
	"\tstart_lng\x18\b \x01(\x01R\bstartLng\x12\x1b\n" +
	"\tstart_lat\x18\t \x01(\x01R\bstartLat\x12\x17\n" +
	"\aend_lng\x18\n" +
	" \x01(\x01R\x06endLng\x12\x17\n" +
	"\aend_lat\x18\v \x01(\x01R\x06endLat\x127\n" +
	"\froute_points\x18\f \x03(\v2\x14.rpcOrder.RoutePointR\vroutePoints\"x\n" +
	"\n" +
	"TakeCarReq\x12$\n" +
	"\rstartingPoint\x18\x01 \x01(\tR\rstartingPoint\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x10\n" +
	"\x03tid\x18\x04 \x01(\x03R\x03tid\"\xa1\x01\n" +
	"\vTakeCarResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x02R\bdistance\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x18\n" +
	"\aorderNo\x18\x06 \x01(\tR\aorderNo\"Y\n" +
	"\vGrabListReq\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\x03R\bdriverId\x12\x18\n" +
	"\aradiusM\x18\x02 \x01(\x03R\aradiusM\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x9d\x03\n" +
	"\rGrabOrderItem\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bstartLng\x18\x03 \x01(\x01R\bstartLng\x12\x1a\n" +
	"\bstartLat\x18\x04 \x01(\x01R\bstartLat\x12\"\n" +
	"\fstartAddress\x18\x05 \x01(\tR\fstartAddress\x12\x16\n" +
	"\x06endLng\x18\x06 \x01(\x01R\x06endLng\x12\x16\n" +
	"\x06endLat\x18\a \x01(\x01R\x06endLat\x12\x1e\n" +
	"\n" +
	"endAddress\x18\b \x01(\tR\n" +
	"endAddress\x12\x1a\n" +
	"\bdistance\x18\t \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x03R\bduration\x12\x14\n" +
	"\x05price\x18\v \x01(\x01R\x05price\x12\x1c\n" +
	"\texpiresAt\x18\f \x01(\x03R\texpiresAt\x12*\n" +
	"\x10distanceToDriver\x18\r \x01(\x01R\x10distanceToDriver\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x03R\x06status\"?\n" +
	"\fGrabListResp\x12/\n" +
	"\x06orders\x18\x01 \x03(\v2\x17.rpcOrder.GrabOrderItemR\x06orders\"D\n" +
	"\fGrabOrderReq\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\x03R\bdriverId\x12\x18\n" +
	"\aorderNo\x18\x02 \x01(\tR\aorderNo\"O\n" +
	"\rGrabOrderResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\aorderNo\x18\x03 \x01(\tR\aorderNo\"D\n" +
	"\fOrderOverReq\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\x03R\bdriverId\x12\x18\n" +
	"\aorderNo\x18\x02 \x01(\tR\aorderNo\"'\n" +
	"\rOrderOverResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"c\n" +
	"\rStartOrderReq\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\x03R\bdriverId\x12\x18\n" +
	"\aorderNo\x18\x02 \x01(\tR\aorderNo\x12\x1c\n" +
	"\tphoneTail\x18\x03 \x01(\tR\tphoneTail\":\n" +
	"\x0eStartOrderResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"T\n" +
	"\x0eCancelOrderReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x18\n" +
	"\aorderNo\x18\x02 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"#\n" +
	"\x0fCancelOrderResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\".\n" +
	"\x10DriverOngoingReq\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\x03R\bdriverId\"^\n" +
	"\x11DriverOngoingResp\x12\x1a\n" +
	"\bhasOrder\x18\x01 \x01(\bR\bhasOrder\x12-\n" +
	"\x05order\x18\x02 \x01(\v2\x17.rpcOrder.GrabOrderItemR\x05order\"\x89\x03\n" +
	"\x0fUserOngoingItem\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\"\n" +
	"\fstartAddress\x18\x03 \x01(\tR\fstartAddress\x12\x1e\n" +
	"\n" +
	"endAddress\x18\x04 \x01(\tR\n" +
	"endAddress\x12\x1a\n" +
	"\bdistance\x18\x05 \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x03R\bduration\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1a\n" +
	"\bdriverId\x18\b \x01(\x03R\bdriverId\x12\x1e\n" +
	"\n" +
	"driverName\x18\t \x01(\tR\n" +
	"driverName\x12\x1c\n" +
	"\tcarNumber\x18\n" +
	" \x01(\tR\tcarNumber\x12\x18\n" +
	"\acarType\x18\v \x01(\tR\acarType\x12\"\n" +
	"\fdriverRating\x18\f \x01(\x01R\fdriverRating\x12\x1a\n" +
	"\bacceptAt\x18\r \x01(\x03R\bacceptAt\"\"\n" +
	"\x0eUserOngoingReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"^\n" +
	"\x0fUserOngoingResp\x12\x1a\n" +
	"\bhasOrder\x18\x01 \x01(\bR\bhasOrder\x12/\n" +
	"\x05order\x18\x02 \x01(\v2\x19.rpcOrder.UserOngoingItemR\x05order2\xba\x05\n" +
	"\bRpcOrder\x12-\n" +
	"\x04Ping\x12\x11.rpcOrder.Request\x1a\x12.rpcOrder.Response\x12E\n" +
	"\fOrderRpcTest\x12\x19.rpcOrder.OrderRpcTestReq\x1a\x1a.rpcOrder.OrderRpcTestResp\x126\n" +
	"\aJourney\x12\x14.rpcOrder.JourneyReq\x1a\x15.rpcOrder.JourneyResp\x126\n" +
	"\aTakeCar\x12\x14.rpcOrder.TakeCarReq\x1a\x15.rpcOrder.TakeCarResp\x129\n" +
	"\bGrabList\x12\x15.rpcOrder.GrabListReq\x1a\x16.rpcOrder.GrabListResp\x12<\n" +
	"\tGrabOrder\x12\x16.rpcOrder.GrabOrderReq\x1a\x17.rpcOrder.GrabOrderResp\x12<\n" +
	"\tOrderOver\x12\x16.rpcOrder.OrderOverReq\x1a\x17.rpcOrder.OrderOverResp\x12?\n" +
	"\n" +
	"StartOrder\x12\x17.rpcOrder.StartOrderReq\x1a\x18.rpcOrder.StartOrderResp\x12B\n" +
	"\vCancelOrder\x12\x18.rpcOrder.CancelOrderReq\x1a\x19.rpcOrder.CancelOrderResp\x12H\n" +
	"\rDriverOngoing\x12\x1a.rpcOrder.DriverOngoingReq\x1a\x1b.rpcOrder.DriverOngoingResp\x12B\n" +
	"\vUserOngoing\x12\x18.rpcOrder.UserOngoingReq\x1a\x19.rpcOrder.UserOngoingRespB\fZ\n" +
	"./rpcOrderb\x06proto3"

var (
	file_rpcOrder_proto_rawDescOnce sync.Once
	file_rpcOrder_proto_rawDescData []byte
)

func file_rpcOrder_proto_rawDescGZIP() []byte {
	file_rpcOrder_proto_rawDescOnce.Do(func() {
		file_rpcOrder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcOrder_proto_rawDesc), len(file_rpcOrder_proto_rawDesc)))
	})
	return file_rpcOrder_proto_rawDescData
}

var file_rpcOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_rpcOrder_proto_goTypes = []any{
	(*Request)(nil),           // 0: rpcOrder.Request
	(*Response)(nil),          // 1: rpcOrder.Response
	(*OrderRpcTestReq)(nil),   // 2: rpcOrder.OrderRpcTestReq
	(*OrderRpcTestResp)(nil),  // 3: rpcOrder.OrderRpcTestResp
	(*JourneyReq)(nil),        // 4: rpcOrder.JourneyReq
	(*RoutePoint)(nil),        // 5: rpcOrder.RoutePoint
	(*JourneyResp)(nil),       // 6: rpcOrder.JourneyResp
	(*TakeCarReq)(nil),        // 7: rpcOrder.TakeCarReq
	(*TakeCarResp)(nil),       // 8: rpcOrder.TakeCarResp
	(*GrabListReq)(nil),       // 9: rpcOrder.GrabListReq
	(*GrabOrderItem)(nil),     // 10: rpcOrder.GrabOrderItem
	(*GrabListResp)(nil),      // 11: rpcOrder.GrabListResp
	(*GrabOrderReq)(nil),      // 12: rpcOrder.GrabOrderReq
	(*GrabOrderResp)(nil),     // 13: rpcOrder.GrabOrderResp
	(*OrderOverReq)(nil),      // 14: rpcOrder.OrderOverReq
	(*OrderOverResp)(nil),     // 15: rpcOrder.OrderOverResp
	(*StartOrderReq)(nil),     // 16: rpcOrder.StartOrderReq
	(*StartOrderResp)(nil),    // 17: rpcOrder.StartOrderResp
	(*CancelOrderReq)(nil),    // 18: rpcOrder.CancelOrderReq
	(*CancelOrderResp)(nil),   // 19: rpcOrder.CancelOrderResp
	(*DriverOngoingReq)(nil),  // 20: rpcOrder.DriverOngoingReq
	(*DriverOngoingResp)(nil), // 21: rpcOrder.DriverOngoingResp
	(*UserOngoingItem)(nil),   // 22: rpcOrder.UserOngoingItem
	(*UserOngoingReq)(nil),    // 23: rpcOrder.UserOngoingReq
	(*UserOngoingResp)(nil),   // 24: rpcOrder.UserOngoingResp
}
var file_rpcOrder_proto_depIdxs = []int32{
	5,  // 0: rpcOrder.JourneyResp.route_points:type_name -> rpcOrder.RoutePoint
	10, // 1: rpcOrder.GrabListResp.orders:type_name -> rpcOrder.GrabOrderItem
	10, // 2: rpcOrder.DriverOngoingResp.order:type_name -> rpcOrder.GrabOrderItem
	22, // 3: rpcOrder.UserOngoingResp.order:type_name -> rpcOrder.UserOngoingItem
	0,  // 4: rpcOrder.RpcOrder.Ping:input_type -> rpcOrder.Request
	2,  // 5: rpcOrder.RpcOrder.OrderRpcTest:input_type -> rpcOrder.OrderRpcTestReq
	4,  // 6: rpcOrder.RpcOrder.Journey:input_type -> rpcOrder.JourneyReq
	7,  // 7: rpcOrder.RpcOrder.TakeCar:input_type -> rpcOrder.TakeCarReq
	9,  // 8: rpcOrder.RpcOrder.GrabList:input_type -> rpcOrder.GrabListReq
	12, // 9: rpcOrder.RpcOrder.GrabOrder:input_type -> rpcOrder.GrabOrderReq
	14, // 10: rpcOrder.RpcOrder.OrderOver:input_type -> rpcOrder.OrderOverReq
	16, // 11: rpcOrder.RpcOrder.StartOrder:input_type -> rpcOrder.StartOrderReq
	18, // 12: rpcOrder.RpcOrder.CancelOrder:input_type -> rpcOrder.CancelOrderReq
	20, // 13: rpcOrder.RpcOrder.DriverOngoing:input_type -> rpcOrder.DriverOngoingReq
	23, // 14: rpcOrder.RpcOrder.UserOngoing:input_type -> rpcOrder.UserOngoingReq
	1,  // 15: rpcOrder.RpcOrder.Ping:output_type -> rpcOrder.Response
	3,  // 16: rpcOrder.RpcOrder.OrderRpcTest:output_type -> rpcOrder.OrderRpcTestResp
	6,  // 17: rpcOrder.RpcOrder.Journey:output_type -> rpcOrder.JourneyResp
	8,  // 18: rpcOrder.RpcOrder.TakeCar:output_type -> rpcOrder.TakeCarResp
	11, // 19: rpcOrder.RpcOrder.GrabList:output_type -> rpcOrder.GrabListResp
	13, // 20: rpcOrder.RpcOrder.GrabOrder:output_type -> rpcOrder.GrabOrderResp
	15, // 21: rpcOrder.RpcOrder.OrderOver:output_type -> rpcOrder.OrderOverResp
	17, // 22: rpcOrder.RpcOrder.StartOrder:output_type -> rpcOrder.StartOrderResp
	19, // 23: rpcOrder.RpcOrder.CancelOrder:output_type -> rpcOrder.CancelOrderResp
	21, // 24: rpcOrder.RpcOrder.DriverOngoing:output_type -> rpcOrder.DriverOngoingResp
	24, // 25: rpcOrder.RpcOrder.UserOngoing:output_type -> rpcOrder.UserOngoingResp
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpcOrder_proto_init() }
func file_rpcOrder_proto_init() {
	if File_rpcOrder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcOrder_proto_rawDesc), len(file_rpcOrder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcOrder_proto_goTypes,
		DependencyIndexes: file_rpcOrder_proto_depIdxs,
		MessageInfos:      file_rpcOrder_proto_msgTypes,
	}.Build()
	File_rpcOrder_proto = out.File
	file_rpcOrder_proto_goTypes = nil
	file_rpcOrder_proto_depIdxs = nil
}
