// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: rpcOrder.proto

package rpcOrder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcOrder_Ping_FullMethodName          = "/rpcOrder.RpcOrder/Ping"
	RpcOrder_OrderRpcTest_FullMethodName  = "/rpcOrder.RpcOrder/OrderRpcTest"
	RpcOrder_Journey_FullMethodName       = "/rpcOrder.RpcOrder/Journey"
	RpcOrder_TakeCar_FullMethodName       = "/rpcOrder.RpcOrder/TakeCar"
	RpcOrder_GrabList_FullMethodName      = "/rpcOrder.RpcOrder/GrabList"
	RpcOrder_GrabOrder_FullMethodName     = "/rpcOrder.RpcOrder/GrabOrder"
	RpcOrder_OrderOver_FullMethodName     = "/rpcOrder.RpcOrder/OrderOver"
	RpcOrder_StartOrder_FullMethodName    = "/rpcOrder.RpcOrder/StartOrder"
	RpcOrder_CancelOrder_FullMethodName   = "/rpcOrder.RpcOrder/CancelOrder"
	RpcOrder_DriverOngoing_FullMethodName = "/rpcOrder.RpcOrder/DriverOngoing"
	RpcOrder_UserOngoing_FullMethodName   = "/rpcOrder.RpcOrder/UserOngoing"
)

// RpcOrderClient is the client API for RpcOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcOrderClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	OrderRpcTest(ctx context.Context, in *OrderRpcTestReq, opts ...grpc.CallOption) (*OrderRpcTestResp, error)
	Journey(ctx context.Context, in *JourneyReq, opts ...grpc.CallOption) (*JourneyResp, error)
	TakeCar(ctx context.Context, in *TakeCarReq, opts ...grpc.CallOption) (*TakeCarResp, error)
	GrabList(ctx context.Context, in *GrabListReq, opts ...grpc.CallOption) (*GrabListResp, error)
	GrabOrder(ctx context.Context, in *GrabOrderReq, opts ...grpc.CallOption) (*GrabOrderResp, error)
	OrderOver(ctx context.Context, in *OrderOverReq, opts ...grpc.CallOption) (*OrderOverResp, error)
	StartOrder(ctx context.Context, in *StartOrderReq, opts ...grpc.CallOption) (*StartOrderResp, error)
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
	DriverOngoing(ctx context.Context, in *DriverOngoingReq, opts ...grpc.CallOption) (*DriverOngoingResp, error)
	UserOngoing(ctx context.Context, in *UserOngoingReq, opts ...grpc.CallOption) (*UserOngoingResp, error)
}

type rpcOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcOrderClient(cc grpc.ClientConnInterface) RpcOrderClient {
	return &rpcOrderClient{cc}
}

func (c *rpcOrderClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RpcOrder_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) OrderRpcTest(ctx context.Context, in *OrderRpcTestReq, opts ...grpc.CallOption) (*OrderRpcTestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderRpcTestResp)
	err := c.cc.Invoke(ctx, RpcOrder_OrderRpcTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) Journey(ctx context.Context, in *JourneyReq, opts ...grpc.CallOption) (*JourneyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JourneyResp)
	err := c.cc.Invoke(ctx, RpcOrder_Journey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) TakeCar(ctx context.Context, in *TakeCarReq, opts ...grpc.CallOption) (*TakeCarResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeCarResp)
	err := c.cc.Invoke(ctx, RpcOrder_TakeCar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) GrabList(ctx context.Context, in *GrabListReq, opts ...grpc.CallOption) (*GrabListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrabListResp)
	err := c.cc.Invoke(ctx, RpcOrder_GrabList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) GrabOrder(ctx context.Context, in *GrabOrderReq, opts ...grpc.CallOption) (*GrabOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrabOrderResp)
	err := c.cc.Invoke(ctx, RpcOrder_GrabOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) OrderOver(ctx context.Context, in *OrderOverReq, opts ...grpc.CallOption) (*OrderOverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderOverResp)
	err := c.cc.Invoke(ctx, RpcOrder_OrderOver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) StartOrder(ctx context.Context, in *StartOrderReq, opts ...grpc.CallOption) (*StartOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOrderResp)
	err := c.cc.Invoke(ctx, RpcOrder_StartOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResp)
	err := c.cc.Invoke(ctx, RpcOrder_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) DriverOngoing(ctx context.Context, in *DriverOngoingReq, opts ...grpc.CallOption) (*DriverOngoingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverOngoingResp)
	err := c.cc.Invoke(ctx, RpcOrder_DriverOngoing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcOrderClient) UserOngoing(ctx context.Context, in *UserOngoingReq, opts ...grpc.CallOption) (*UserOngoingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserOngoingResp)
	err := c.cc.Invoke(ctx, RpcOrder_UserOngoing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcOrderServer is the server API for RpcOrder service.
// All implementations must embed UnimplementedRpcOrderServer
// for forward compatibility.
type RpcOrderServer interface {
	Ping(context.Context, *Request) (*Response, error)
	OrderRpcTest(context.Context, *OrderRpcTestReq) (*OrderRpcTestResp, error)
	Journey(context.Context, *JourneyReq) (*JourneyResp, error)
	TakeCar(context.Context, *TakeCarReq) (*TakeCarResp, error)
	GrabList(context.Context, *GrabListReq) (*GrabListResp, error)
	GrabOrder(context.Context, *GrabOrderReq) (*GrabOrderResp, error)
	OrderOver(context.Context, *OrderOverReq) (*OrderOverResp, error)
	StartOrder(context.Context, *StartOrderReq) (*StartOrderResp, error)
	CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderResp, error)
	DriverOngoing(context.Context, *DriverOngoingReq) (*DriverOngoingResp, error)
	UserOngoing(context.Context, *UserOngoingReq) (*UserOngoingResp, error)
	mustEmbedUnimplementedRpcOrderServer()
}

// UnimplementedRpcOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcOrderServer struct{}

func (UnimplementedRpcOrderServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcOrderServer) OrderRpcTest(context.Context, *OrderRpcTestReq) (*OrderRpcTestResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OrderRpcTest not implemented")
}
func (UnimplementedRpcOrderServer) Journey(context.Context, *JourneyReq) (*JourneyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Journey not implemented")
}
func (UnimplementedRpcOrderServer) TakeCar(context.Context, *TakeCarReq) (*TakeCarResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TakeCar not implemented")
}
func (UnimplementedRpcOrderServer) GrabList(context.Context, *GrabListReq) (*GrabListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GrabList not implemented")
}
func (UnimplementedRpcOrderServer) GrabOrder(context.Context, *GrabOrderReq) (*GrabOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GrabOrder not implemented")
}
func (UnimplementedRpcOrderServer) OrderOver(context.Context, *OrderOverReq) (*OrderOverResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OrderOver not implemented")
}
func (UnimplementedRpcOrderServer) StartOrder(context.Context, *StartOrderReq) (*StartOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartOrder not implemented")
}
func (UnimplementedRpcOrderServer) CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedRpcOrderServer) DriverOngoing(context.Context, *DriverOngoingReq) (*DriverOngoingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverOngoing not implemented")
}
func (UnimplementedRpcOrderServer) UserOngoing(context.Context, *UserOngoingReq) (*UserOngoingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserOngoing not implemented")
}
func (UnimplementedRpcOrderServer) mustEmbedUnimplementedRpcOrderServer() {}
func (UnimplementedRpcOrderServer) testEmbeddedByValue()                  {}

// UnsafeRpcOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcOrderServer will
// result in compilation errors.
type UnsafeRpcOrderServer interface {
	mustEmbedUnimplementedRpcOrderServer()
}

func RegisterRpcOrderServer(s grpc.ServiceRegistrar, srv RpcOrderServer) {
	// If the following call panics, it indicates UnimplementedRpcOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcOrder_ServiceDesc, srv)
}

func _RpcOrder_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_OrderRpcTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRpcTestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).OrderRpcTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_OrderRpcTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).OrderRpcTest(ctx, req.(*OrderRpcTestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_Journey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JourneyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).Journey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_Journey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).Journey(ctx, req.(*JourneyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_TakeCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeCarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).TakeCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_TakeCar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).TakeCar(ctx, req.(*TakeCarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_GrabList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrabListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).GrabList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_GrabList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).GrabList(ctx, req.(*GrabListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_GrabOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrabOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).GrabOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_GrabOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).GrabOrder(ctx, req.(*GrabOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_OrderOver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderOverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).OrderOver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_OrderOver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).OrderOver(ctx, req.(*OrderOverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_StartOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).StartOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_StartOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).StartOrder(ctx, req.(*StartOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_DriverOngoing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverOngoingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).DriverOngoing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_DriverOngoing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).DriverOngoing(ctx, req.(*DriverOngoingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcOrder_UserOngoing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOngoingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).UserOngoing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcOrder_UserOngoing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).UserOngoing(ctx, req.(*UserOngoingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcOrder_ServiceDesc is the grpc.ServiceDesc for RpcOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcOrder.RpcOrder",
	HandlerType: (*RpcOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RpcOrder_Ping_Handler,
		},
		{
			MethodName: "OrderRpcTest",
			Handler:    _RpcOrder_OrderRpcTest_Handler,
		},
		{
			MethodName: "Journey",
			Handler:    _RpcOrder_Journey_Handler,
		},
		{
			MethodName: "TakeCar",
			Handler:    _RpcOrder_TakeCar_Handler,
		},
		{
			MethodName: "GrabList",
			Handler:    _RpcOrder_GrabList_Handler,
		},
		{
			MethodName: "GrabOrder",
			Handler:    _RpcOrder_GrabOrder_Handler,
		},
		{
			MethodName: "OrderOver",
			Handler:    _RpcOrder_OrderOver_Handler,
		},
		{
			MethodName: "StartOrder",
			Handler:    _RpcOrder_StartOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _RpcOrder_CancelOrder_Handler,
		},
		{
			MethodName: "DriverOngoing",
			Handler:    _RpcOrder_DriverOngoing_Handler,
		},
		{
			MethodName: "UserOngoing",
			Handler:    _RpcOrder_UserOngoing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcOrder.proto",
}
