// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"apiGateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/driver/login",
				Handler: DriverLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/driver/register",
				Handler: DriverRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/driver/rpc/test",
				Handler: DriverRpcTestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/driver/sms",
				Handler: DriverSmsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: ApiGatewayHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/rpc/test",
				Handler: MapRpcTestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/rpc/test",
				Handler: OrderRpcTestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/balance/notify",
				Handler: UserBalanceNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/rpc/test",
				Handler: UserRpcTestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/sms",
				Handler: UserSmsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/rpc/test",
					Handler: AuthRpcTestHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/driver/auth/map/chat",
					Handler: DriverMapChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/driver/auth/offline",
					Handler: DriverOfflineHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/driver/auth/order/list",
					Handler: DriverOrderListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/driver/auth/order/rating",
					Handler: DriverOrderRatingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/driver/auth/real/name",
					Handler: DriverRealNameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/driver/auth/real/name/status",
					Handler: DriverRealNameStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/driver/auth/wallet/balance",
					Handler: DriverWalletBalanceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/driver/auth/wallet/logs",
					Handler: DriverWalletLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/map/auth/get/coordinates",
					Handler: MapGetCoordinatesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/map/auth/issue/coupons",
					Handler: MapIssueCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/map/auth/reverse/geocode",
					Handler: MapReverseGeocodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/auth/cancel/order",
					Handler: OrderCancelOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/auth/driver/ongoing",
					Handler: OrderDriverOngoingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/auth/grab/list",
					Handler: OrderGrabListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/auth/grab/order",
					Handler: OrderGrabOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/auth/journey",
					Handler: OrderJourneyHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/auth/order/over",
					Handler: OrderOverHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/auth/start/order",
					Handler: OrderStartOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/auth/take/car",
					Handler: OrderTakeCarHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/auth/user/ongoing",
					Handler: OrderUserOngoingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/alipay/balance",
					Handler: UserAliPayBalanceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/list/coupons",
					Handler: UserListCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/map/chat",
					Handler: UserMapChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/order/list",
					Handler: UserOrderListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/order/rating",
					Handler: UserOrderRatingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/order/rating/delete",
					Handler: UserDeleteOrderRatingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/rate/order",
					Handler: UserRateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/real/name",
					Handler: UserRealNameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/real/name/status",
					Handler: UserRealNameStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/wallet/balance",
					Handler: UserWalletBalanceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/auth/wallet/logs",
					Handler: UserWalletLogsHandler(serverCtx),
				},
			}...,
		),
	)
}
