// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpcMap.proto

package server

import (
	"context"

	"rpcMap/internal/logic"
	"rpcMap/internal/svc"
	"rpcMap/rpcMap"
)

type RpcMapServer struct {
	svcCtx *svc.ServiceContext
	rpcMap.UnimplementedRpcMapServer
}

func NewRpcMapServer(svcCtx *svc.ServiceContext) *RpcMapServer {
	return &RpcMapServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcMapServer) Ping(ctx context.Context, in *rpcMap.Request) (*rpcMap.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *RpcMapServer) MapRpcTest(ctx context.Context, in *rpcMap.MapRpcTestReq) (*rpcMap.MapRpcTestResp, error) {
	l := logic.NewMapRpcTestLogic(ctx, s.svcCtx)
	return l.MapRpcTest(in)
}

func (s *RpcMapServer) GetCoordinates(ctx context.Context, in *rpcMap.GetCoordinatesReq) (*rpcMap.GetCoordinatesResp, error) {
	l := logic.NewGetCoordinatesLogic(ctx, s.svcCtx)
	return l.GetCoordinates(in)
}

func (s *RpcMapServer) ReverseGeocode(ctx context.Context, in *rpcMap.ReverseGeocodeReq) (*rpcMap.ReverseGeocodeResp, error) {
	l := logic.NewReverseGeocodeLogic(ctx, s.svcCtx)
	return l.ReverseGeocode(in)
}

func (s *RpcMapServer) IssueCoupons(ctx context.Context, in *rpcMap.IssueCouponsReq) (*rpcMap.IssueCouponsResp, error) {
	l := logic.NewIssueCouponsLogic(ctx, s.svcCtx)
	return l.IssueCoupons(in)
}

func (s *RpcMapServer) MapChat(ctx context.Context, in *rpcMap.MapChatReq) (*rpcMap.MapChatResp, error) {
	l := logic.NewMapChatLogic(ctx, s.svcCtx)
	return l.MapChat(in)
}
