// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpcDriver.proto

package server

import (
	"context"

	"rpcDriver/internal/logic"
	"rpcDriver/internal/svc"
	"rpcDriver/rpcDriver"
)

type RpcDriverServer struct {
	svcCtx *svc.ServiceContext
	rpcDriver.UnimplementedRpcDriverServer
}

func NewRpcDriverServer(svcCtx *svc.ServiceContext) *RpcDriverServer {
	return &RpcDriverServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcDriverServer) Ping(ctx context.Context, in *rpcDriver.Request) (*rpcDriver.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *RpcDriverServer) DriverRpcTest(ctx context.Context, in *rpcDriver.DriverRpcTestReq) (*rpcDriver.DriverRpcTestResp, error) {
	l := logic.NewDriverRpcTestLogic(ctx, s.svcCtx)
	return l.DriverRpcTest(in)
}

func (s *RpcDriverServer) Sms(ctx context.Context, in *rpcDriver.SmsReq) (*rpcDriver.SmsResp, error) {
	l := logic.NewSmsLogic(ctx, s.svcCtx)
	return l.Sms(in)
}

func (s *RpcDriverServer) DriverReg(ctx context.Context, in *rpcDriver.DriverRegReq) (*rpcDriver.DriverRegResp, error) {
	l := logic.NewDriverRegLogic(ctx, s.svcCtx)
	return l.DriverReg(in)
}

func (s *RpcDriverServer) DriverLogin(ctx context.Context, in *rpcDriver.DriverLoginReq) (*rpcDriver.DriverLoginResp, error) {
	l := logic.NewDriverLoginLogic(ctx, s.svcCtx)
	return l.DriverLogin(in)
}

func (s *RpcDriverServer) RealName(ctx context.Context, in *rpcDriver.RealNameReq) (*rpcDriver.RealNameResp, error) {
	l := logic.NewRealNameLogic(ctx, s.svcCtx)
	return l.RealName(in)
}

func (s *RpcDriverServer) GetRealNameStatus(ctx context.Context, in *rpcDriver.GetRealNameStatusReq) (*rpcDriver.GetRealNameStatusResp, error) {
	l := logic.NewGetRealNameStatusLogic(ctx, s.svcCtx)
	return l.GetRealNameStatus(in)
}

func (s *RpcDriverServer) Offline(ctx context.Context, in *rpcDriver.DriverOfflineReq) (*rpcDriver.DriverOfflineResp, error) {
	l := logic.NewOfflineLogic(ctx, s.svcCtx)
	return l.Offline(in)
}

func (s *RpcDriverServer) GetWalletBalance(ctx context.Context, in *rpcDriver.GetWalletBalanceReq) (*rpcDriver.GetWalletBalanceResp, error) {
	l := logic.NewGetWalletBalanceLogic(ctx, s.svcCtx)
	return l.GetWalletBalance(in)
}

func (s *RpcDriverServer) ListWalletLogs(ctx context.Context, in *rpcDriver.ListWalletLogsReq) (*rpcDriver.ListWalletLogsResp, error) {
	l := logic.NewListWalletLogsLogic(ctx, s.svcCtx)
	return l.ListWalletLogs(in)
}

func (s *RpcDriverServer) ListOrders(ctx context.Context, in *rpcDriver.ListOrdersReq) (*rpcDriver.ListOrdersResp, error) {
	l := logic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

func (s *RpcDriverServer) GetOrderRating(ctx context.Context, in *rpcDriver.GetOrderRatingReq) (*rpcDriver.GetOrderRatingResp, error) {
	l := logic.NewGetOrderRatingLogic(ctx, s.svcCtx)
	return l.GetOrderRating(in)
}
