// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpcMap.proto

package rpcMap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_rpcMap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_rpcMap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type MapRpcTestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapRpcTestReq) Reset() {
	*x = MapRpcTestReq{}
	mi := &file_rpcMap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapRpcTestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRpcTestReq) ProtoMessage() {}

func (x *MapRpcTestReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRpcTestReq.ProtoReflect.Descriptor instead.
func (*MapRpcTestReq) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{2}
}

func (x *MapRpcTestReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MapRpcTestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapRpcTestResp) Reset() {
	*x = MapRpcTestResp{}
	mi := &file_rpcMap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapRpcTestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRpcTestResp) ProtoMessage() {}

func (x *MapRpcTestResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRpcTestResp.ProtoReflect.Descriptor instead.
func (*MapRpcTestResp) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{3}
}

func (x *MapRpcTestResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetCoordinatesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Type          int64                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoordinatesReq) Reset() {
	*x = GetCoordinatesReq{}
	mi := &file_rpcMap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoordinatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoordinatesReq) ProtoMessage() {}

func (x *GetCoordinatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoordinatesReq.ProtoReflect.Descriptor instead.
func (*GetCoordinatesReq) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{4}
}

func (x *GetCoordinatesReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetCoordinatesReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetCoordinatesReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetCoordinatesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoordinatesResp) Reset() {
	*x = GetCoordinatesResp{}
	mi := &file_rpcMap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoordinatesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoordinatesResp) ProtoMessage() {}

func (x *GetCoordinatesResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoordinatesResp.ProtoReflect.Descriptor instead.
func (*GetCoordinatesResp) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{5}
}

func (x *GetCoordinatesResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetCoordinatesResp) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *GetCoordinatesResp) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

// IssueCouponsReq 公司账户按地址向同城用户批量发券
type IssueCouponsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 目标地区地址（地理编码 → 城市 adcode）
	Type          int64                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`      // 1现金券 2折扣券 3免费乘车券
	MoneyQuan     float64                `protobuf:"fixed64,3,opt,name=money_quan,json=moneyQuan,proto3" json:"money_quan,omitempty"`
	Discount      float64                `protobuf:"fixed64,4,opt,name=discount,proto3" json:"discount,omitempty"`
	OutTime       string                 `protobuf:"bytes,5,opt,name=out_time,json=outTime,proto3" json:"out_time,omitempty"` // 过期时间 2006-01-02 15:04:05
	OperatorUid   int64                  `protobuf:"varint,6,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponsReq) Reset() {
	*x = IssueCouponsReq{}
	mi := &file_rpcMap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponsReq) ProtoMessage() {}

func (x *IssueCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponsReq.ProtoReflect.Descriptor instead.
func (*IssueCouponsReq) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{6}
}

func (x *IssueCouponsReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IssueCouponsReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *IssueCouponsReq) GetMoneyQuan() float64 {
	if x != nil {
		return x.MoneyQuan
	}
	return 0
}

func (x *IssueCouponsReq) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *IssueCouponsReq) GetOutTime() string {
	if x != nil {
		return x.OutTime
	}
	return ""
}

func (x *IssueCouponsReq) GetOperatorUid() int64 {
	if x != nil {
		return x.OperatorUid
	}
	return 0
}

type IssueCouponsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CityCode      string                 `protobuf:"bytes,2,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	CityName      string                 `protobuf:"bytes,3,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	IssuedCount   int32                  `protobuf:"varint,4,opt,name=issued_count,json=issuedCount,proto3" json:"issued_count,omitempty"`
	SkippedCount  int32                  `protobuf:"varint,5,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponsResp) Reset() {
	*x = IssueCouponsResp{}
	mi := &file_rpcMap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponsResp) ProtoMessage() {}

func (x *IssueCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponsResp.ProtoReflect.Descriptor instead.
func (*IssueCouponsResp) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{7}
}

func (x *IssueCouponsResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IssueCouponsResp) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *IssueCouponsResp) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *IssueCouponsResp) GetIssuedCount() int32 {
	if x != nil {
		return x.IssuedCount
	}
	return 0
}

func (x *IssueCouponsResp) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

type ReverseGeocodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lng           float64                `protobuf:"fixed64,1,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeReq) Reset() {
	*x = ReverseGeocodeReq{}
	mi := &file_rpcMap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeReq) ProtoMessage() {}

func (x *ReverseGeocodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeReq.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeReq) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{8}
}

func (x *ReverseGeocodeReq) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *ReverseGeocodeReq) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ReverseGeocodeReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ReverseGeocodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeResp) Reset() {
	*x = ReverseGeocodeResp{}
	mi := &file_rpcMap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeResp) ProtoMessage() {}

func (x *ReverseGeocodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeResp.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeResp) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{9}
}

func (x *ReverseGeocodeResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReverseGeocodeResp) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *ReverseGeocodeResp) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type MapChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 1=闲聊 2=业务助手
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`   // 网关从 token 注入，type=2 时必填
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"` // 1=乘客 2=司机，type=2 时必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChatReq) Reset() {
	*x = MapChatReq{}
	mi := &file_rpcMap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChatReq) ProtoMessage() {}

func (x *MapChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChatReq.ProtoReflect.Descriptor instead.
func (*MapChatReq) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{10}
}

func (x *MapChatReq) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *MapChatReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MapChatReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MapChatReq) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type MapChatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChatResp) Reset() {
	*x = MapChatResp{}
	mi := &file_rpcMap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChatResp) ProtoMessage() {}

func (x *MapChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcMap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChatResp.ProtoReflect.Descriptor instead.
func (*MapChatResp) Descriptor() ([]byte, []int) {
	return file_rpcMap_proto_rawDescGZIP(), []int{11}
}

func (x *MapChatResp) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_rpcMap_proto protoreflect.FileDescriptor

const file_rpcMap_proto_rawDesc = "" +
	"\n" +
	"\frpcMap.proto\x12\x06rpcMap\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"!\n" +
	"\rMapRpcTestReq\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"(\n" +
	"\x0eMapRpcTestResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"S\n" +
	"\x11GetCoordinatesReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x03R\x04type\"R\n" +
	"\x12GetCoordinatesResp\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\"\xb8\x01\n" +
	"\x0fIssueCouponsReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x03R\x04type\x12\x1d\n" +
	"\n" +
	"money_quan\x18\x03 \x01(\x01R\tmoneyQuan\x12\x1a\n" +
	"\bdiscount\x18\x04 \x01(\x01R\bdiscount\x12\x19\n" +
	"\bout_time\x18\x05 \x01(\tR\aoutTime\x12!\n" +
	"\foperator_uid\x18\x06 \x01(\x03R\voperatorUid\"\xac\x01\n" +
	"\x10IssueCouponsResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tcity_code\x18\x02 \x01(\tR\bcityCode\x12\x1b\n" +
	"\tcity_name\x18\x03 \x01(\tR\bcityName\x12!\n" +
	"\fissued_count\x18\x04 \x01(\x05R\vissuedCount\x12#\n" +
	"\rskipped_count\x18\x05 \x01(\x05R\fskippedCount\"I\n" +
	"\x11ReverseGeocodeReq\x12\x10\n" +
	"\x03lng\x18\x01 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\"R\n" +
	"\x12ReverseGeocodeResp\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\"b\n" +
	"\n" +
	"MapChatReq\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\"%\n" +
	"\vMapChatResp\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer2\xf9\x02\n" +
	"\x06RpcMap\x12)\n" +
	"\x04Ping\x12\x0f.rpcMap.Request\x1a\x10.rpcMap.Response\x12;\n" +
	"\n" +
	"MapRpcTest\x12\x15.rpcMap.MapRpcTestReq\x1a\x16.rpcMap.MapRpcTestResp\x12G\n" +
	"\x0eGetCoordinates\x12\x19.rpcMap.GetCoordinatesReq\x1a\x1a.rpcMap.GetCoordinatesResp\x12G\n" +
	"\x0eReverseGeocode\x12\x19.rpcMap.ReverseGeocodeReq\x1a\x1a.rpcMap.ReverseGeocodeResp\x12A\n" +
	"\fIssueCoupons\x12\x17.rpcMap.IssueCouponsReq\x1a\x18.rpcMap.IssueCouponsResp\x122\n" +
	"\aMapChat\x12\x12.rpcMap.MapChatReq\x1a\x13.rpcMap.MapChatRespB\n" +
	"Z\b./rpcMapb\x06proto3"

var (
	file_rpcMap_proto_rawDescOnce sync.Once
	file_rpcMap_proto_rawDescData []byte
)

func file_rpcMap_proto_rawDescGZIP() []byte {
	file_rpcMap_proto_rawDescOnce.Do(func() {
		file_rpcMap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcMap_proto_rawDesc), len(file_rpcMap_proto_rawDesc)))
	})
	return file_rpcMap_proto_rawDescData
}

var file_rpcMap_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rpcMap_proto_goTypes = []any{
	(*Request)(nil),            // 0: rpcMap.Request
	(*Response)(nil),           // 1: rpcMap.Response
	(*MapRpcTestReq)(nil),      // 2: rpcMap.MapRpcTestReq
	(*MapRpcTestResp)(nil),     // 3: rpcMap.MapRpcTestResp
	(*GetCoordinatesReq)(nil),  // 4: rpcMap.GetCoordinatesReq
	(*GetCoordinatesResp)(nil), // 5: rpcMap.GetCoordinatesResp
	(*IssueCouponsReq)(nil),    // 6: rpcMap.IssueCouponsReq
	(*IssueCouponsResp)(nil),   // 7: rpcMap.IssueCouponsResp
	(*ReverseGeocodeReq)(nil),  // 8: rpcMap.ReverseGeocodeReq
	(*ReverseGeocodeResp)(nil), // 9: rpcMap.ReverseGeocodeResp
	(*MapChatReq)(nil),         // 10: rpcMap.MapChatReq
	(*MapChatResp)(nil),        // 11: rpcMap.MapChatResp
}
var file_rpcMap_proto_depIdxs = []int32{
	0,  // 0: rpcMap.RpcMap.Ping:input_type -> rpcMap.Request
	2,  // 1: rpcMap.RpcMap.MapRpcTest:input_type -> rpcMap.MapRpcTestReq
	4,  // 2: rpcMap.RpcMap.GetCoordinates:input_type -> rpcMap.GetCoordinatesReq
	8,  // 3: rpcMap.RpcMap.ReverseGeocode:input_type -> rpcMap.ReverseGeocodeReq
	6,  // 4: rpcMap.RpcMap.IssueCoupons:input_type -> rpcMap.IssueCouponsReq
	10, // 5: rpcMap.RpcMap.MapChat:input_type -> rpcMap.MapChatReq
	1,  // 6: rpcMap.RpcMap.Ping:output_type -> rpcMap.Response
	3,  // 7: rpcMap.RpcMap.MapRpcTest:output_type -> rpcMap.MapRpcTestResp
	5,  // 8: rpcMap.RpcMap.GetCoordinates:output_type -> rpcMap.GetCoordinatesResp
	9,  // 9: rpcMap.RpcMap.ReverseGeocode:output_type -> rpcMap.ReverseGeocodeResp
	7,  // 10: rpcMap.RpcMap.IssueCoupons:output_type -> rpcMap.IssueCouponsResp
	11, // 11: rpcMap.RpcMap.MapChat:output_type -> rpcMap.MapChatResp
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpcMap_proto_init() }
func file_rpcMap_proto_init() {
	if File_rpcMap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcMap_proto_rawDesc), len(file_rpcMap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcMap_proto_goTypes,
		DependencyIndexes: file_rpcMap_proto_depIdxs,
		MessageInfos:      file_rpcMap_proto_msgTypes,
	}.Build()
	File_rpcMap_proto = out.File
	file_rpcMap_proto_goTypes = nil
	file_rpcMap_proto_depIdxs = nil
}
