// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: rpcMap.proto

package rpcMap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcMap_Ping_FullMethodName           = "/rpcMap.RpcMap/Ping"
	RpcMap_MapRpcTest_FullMethodName     = "/rpcMap.RpcMap/MapRpcTest"
	RpcMap_GetCoordinates_FullMethodName = "/rpcMap.RpcMap/GetCoordinates"
	RpcMap_ReverseGeocode_FullMethodName = "/rpcMap.RpcMap/ReverseGeocode"
	RpcMap_IssueCoupons_FullMethodName   = "/rpcMap.RpcMap/IssueCoupons"
	RpcMap_MapChat_FullMethodName        = "/rpcMap.RpcMap/MapChat"
)

// RpcMapClient is the client API for RpcMap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcMapClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	MapRpcTest(ctx context.Context, in *MapRpcTestReq, opts ...grpc.CallOption) (*MapRpcTestResp, error)
	GetCoordinates(ctx context.Context, in *GetCoordinatesReq, opts ...grpc.CallOption) (*GetCoordinatesResp, error)
	ReverseGeocode(ctx context.Context, in *ReverseGeocodeReq, opts ...grpc.CallOption) (*ReverseGeocodeResp, error)
	IssueCoupons(ctx context.Context, in *IssueCouponsReq, opts ...grpc.CallOption) (*IssueCouponsResp, error)
	MapChat(ctx context.Context, in *MapChatReq, opts ...grpc.CallOption) (*MapChatResp, error)
}

type rpcMapClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcMapClient(cc grpc.ClientConnInterface) RpcMapClient {
	return &rpcMapClient{cc}
}

func (c *rpcMapClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RpcMap_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcMapClient) MapRpcTest(ctx context.Context, in *MapRpcTestReq, opts ...grpc.CallOption) (*MapRpcTestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapRpcTestResp)
	err := c.cc.Invoke(ctx, RpcMap_MapRpcTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcMapClient) GetCoordinates(ctx context.Context, in *GetCoordinatesReq, opts ...grpc.CallOption) (*GetCoordinatesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoordinatesResp)
	err := c.cc.Invoke(ctx, RpcMap_GetCoordinates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcMapClient) ReverseGeocode(ctx context.Context, in *ReverseGeocodeReq, opts ...grpc.CallOption) (*ReverseGeocodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseGeocodeResp)
	err := c.cc.Invoke(ctx, RpcMap_ReverseGeocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcMapClient) IssueCoupons(ctx context.Context, in *IssueCouponsReq, opts ...grpc.CallOption) (*IssueCouponsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueCouponsResp)
	err := c.cc.Invoke(ctx, RpcMap_IssueCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcMapClient) MapChat(ctx context.Context, in *MapChatReq, opts ...grpc.CallOption) (*MapChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapChatResp)
	err := c.cc.Invoke(ctx, RpcMap_MapChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcMapServer is the server API for RpcMap service.
// All implementations must embed UnimplementedRpcMapServer
// for forward compatibility.
type RpcMapServer interface {
	Ping(context.Context, *Request) (*Response, error)
	MapRpcTest(context.Context, *MapRpcTestReq) (*MapRpcTestResp, error)
	GetCoordinates(context.Context, *GetCoordinatesReq) (*GetCoordinatesResp, error)
	ReverseGeocode(context.Context, *ReverseGeocodeReq) (*ReverseGeocodeResp, error)
	IssueCoupons(context.Context, *IssueCouponsReq) (*IssueCouponsResp, error)
	MapChat(context.Context, *MapChatReq) (*MapChatResp, error)
	mustEmbedUnimplementedRpcMapServer()
}

// UnimplementedRpcMapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcMapServer struct{}

func (UnimplementedRpcMapServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcMapServer) MapRpcTest(context.Context, *MapRpcTestReq) (*MapRpcTestResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MapRpcTest not implemented")
}
func (UnimplementedRpcMapServer) GetCoordinates(context.Context, *GetCoordinatesReq) (*GetCoordinatesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoordinates not implemented")
}
func (UnimplementedRpcMapServer) ReverseGeocode(context.Context, *ReverseGeocodeReq) (*ReverseGeocodeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseGeocode not implemented")
}
func (UnimplementedRpcMapServer) IssueCoupons(context.Context, *IssueCouponsReq) (*IssueCouponsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueCoupons not implemented")
}
func (UnimplementedRpcMapServer) MapChat(context.Context, *MapChatReq) (*MapChatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MapChat not implemented")
}
func (UnimplementedRpcMapServer) mustEmbedUnimplementedRpcMapServer() {}
func (UnimplementedRpcMapServer) testEmbeddedByValue()                {}

// UnsafeRpcMapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcMapServer will
// result in compilation errors.
type UnsafeRpcMapServer interface {
	mustEmbedUnimplementedRpcMapServer()
}

func RegisterRpcMapServer(s grpc.ServiceRegistrar, srv RpcMapServer) {
	// If the following call panics, it indicates UnimplementedRpcMapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcMap_ServiceDesc, srv)
}

func _RpcMap_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcMapServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcMap_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcMapServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcMap_MapRpcTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapRpcTestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcMapServer).MapRpcTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcMap_MapRpcTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcMapServer).MapRpcTest(ctx, req.(*MapRpcTestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcMap_GetCoordinates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoordinatesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcMapServer).GetCoordinates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcMap_GetCoordinates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcMapServer).GetCoordinates(ctx, req.(*GetCoordinatesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcMap_ReverseGeocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseGeocodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcMapServer).ReverseGeocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcMap_ReverseGeocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcMapServer).ReverseGeocode(ctx, req.(*ReverseGeocodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcMap_IssueCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCouponsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcMapServer).IssueCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcMap_IssueCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcMapServer).IssueCoupons(ctx, req.(*IssueCouponsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcMap_MapChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcMapServer).MapChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcMap_MapChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcMapServer).MapChat(ctx, req.(*MapChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcMap_ServiceDesc is the grpc.ServiceDesc for RpcMap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcMap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcMap.RpcMap",
	HandlerType: (*RpcMapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RpcMap_Ping_Handler,
		},
		{
			MethodName: "MapRpcTest",
			Handler:    _RpcMap_MapRpcTest_Handler,
		},
		{
			MethodName: "GetCoordinates",
			Handler:    _RpcMap_GetCoordinates_Handler,
		},
		{
			MethodName: "ReverseGeocode",
			Handler:    _RpcMap_ReverseGeocode_Handler,
		},
		{
			MethodName: "IssueCoupons",
			Handler:    _RpcMap_IssueCoupons_Handler,
		},
		{
			MethodName: "MapChat",
			Handler:    _RpcMap_MapChat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcMap.proto",
}
