// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpcUser.proto

package rpcuserclient

import (
	"context"

	"rpcUser/rpcUser"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AliPayBalanceReq      = rpcUser.AliPayBalanceReq
	AliPayBalanceResp     = rpcUser.AliPayBalanceResp
	BalanceNotifyReq      = rpcUser.BalanceNotifyReq
	BalanceNotifyResp     = rpcUser.BalanceNotifyResp
	CouponItem            = rpcUser.CouponItem
	DeleteOrderRatingReq  = rpcUser.DeleteOrderRatingReq
	DeleteOrderRatingResp = rpcUser.DeleteOrderRatingResp
	GetOrderRatingReq     = rpcUser.GetOrderRatingReq
	GetOrderRatingResp    = rpcUser.GetOrderRatingResp
	GetRealNameStatusReq  = rpcUser.GetRealNameStatusReq
	GetRealNameStatusResp = rpcUser.GetRealNameStatusResp
	GetWalletBalanceReq   = rpcUser.GetWalletBalanceReq
	GetWalletBalanceResp  = rpcUser.GetWalletBalanceResp
	ListCouponsReq        = rpcUser.ListCouponsReq
	ListCouponsResp       = rpcUser.ListCouponsResp
	ListOrdersReq         = rpcUser.ListOrdersReq
	ListOrdersResp        = rpcUser.ListOrdersResp
	ListWalletLogsReq     = rpcUser.ListWalletLogsReq
	ListWalletLogsResp    = rpcUser.ListWalletLogsResp
	LoginReq              = rpcUser.LoginReq
	LoginResp             = rpcUser.LoginResp
	OrderListItem         = rpcUser.OrderListItem
	RateOrderReq          = rpcUser.RateOrderReq
	RateOrderResp         = rpcUser.RateOrderResp
	RealNameReq           = rpcUser.RealNameReq
	RealNameResp          = rpcUser.RealNameResp
	RegisterReq           = rpcUser.RegisterReq
	RegisterResp          = rpcUser.RegisterResp
	Request               = rpcUser.Request
	Response              = rpcUser.Response
	SmsReq                = rpcUser.SmsReq
	SmsResp               = rpcUser.SmsResp
	UserRpcTestReq        = rpcUser.UserRpcTestReq
	UserRpcTestResp       = rpcUser.UserRpcTestResp
	WalletLogItem         = rpcUser.WalletLogItem

	RpcUser interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		UserRpcTest(ctx context.Context, in *UserRpcTestReq, opts ...grpc.CallOption) (*UserRpcTestResp, error)
		Sms(ctx context.Context, in *SmsReq, opts ...grpc.CallOption) (*SmsResp, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		RealName(ctx context.Context, in *RealNameReq, opts ...grpc.CallOption) (*RealNameResp, error)
		GetRealNameStatus(ctx context.Context, in *GetRealNameStatusReq, opts ...grpc.CallOption) (*GetRealNameStatusResp, error)
		BalanceNotify(ctx context.Context, in *BalanceNotifyReq, opts ...grpc.CallOption) (*BalanceNotifyResp, error)
		AliPayBalance(ctx context.Context, in *AliPayBalanceReq, opts ...grpc.CallOption) (*AliPayBalanceResp, error)
		ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error)
		RateOrder(ctx context.Context, in *RateOrderReq, opts ...grpc.CallOption) (*RateOrderResp, error)
		GetWalletBalance(ctx context.Context, in *GetWalletBalanceReq, opts ...grpc.CallOption) (*GetWalletBalanceResp, error)
		ListWalletLogs(ctx context.Context, in *ListWalletLogsReq, opts ...grpc.CallOption) (*ListWalletLogsResp, error)
		ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error)
		GetOrderRating(ctx context.Context, in *GetOrderRatingReq, opts ...grpc.CallOption) (*GetOrderRatingResp, error)
		DeleteOrderRating(ctx context.Context, in *DeleteOrderRatingReq, opts ...grpc.CallOption) (*DeleteOrderRatingResp, error)
	}

	defaultRpcUser struct {
		cli zrpc.Client
	}
)

func NewRpcUser(cli zrpc.Client) RpcUser {
	return &defaultRpcUser{
		cli: cli,
	}
}

func (m *defaultRpcUser) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultRpcUser) UserRpcTest(ctx context.Context, in *UserRpcTestReq, opts ...grpc.CallOption) (*UserRpcTestResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.UserRpcTest(ctx, in, opts...)
}

func (m *defaultRpcUser) Sms(ctx context.Context, in *SmsReq, opts ...grpc.CallOption) (*SmsResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.Sms(ctx, in, opts...)
}

func (m *defaultRpcUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultRpcUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultRpcUser) RealName(ctx context.Context, in *RealNameReq, opts ...grpc.CallOption) (*RealNameResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.RealName(ctx, in, opts...)
}

func (m *defaultRpcUser) GetRealNameStatus(ctx context.Context, in *GetRealNameStatusReq, opts ...grpc.CallOption) (*GetRealNameStatusResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.GetRealNameStatus(ctx, in, opts...)
}

func (m *defaultRpcUser) BalanceNotify(ctx context.Context, in *BalanceNotifyReq, opts ...grpc.CallOption) (*BalanceNotifyResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.BalanceNotify(ctx, in, opts...)
}

func (m *defaultRpcUser) AliPayBalance(ctx context.Context, in *AliPayBalanceReq, opts ...grpc.CallOption) (*AliPayBalanceResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.AliPayBalance(ctx, in, opts...)
}

func (m *defaultRpcUser) ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.ListCoupons(ctx, in, opts...)
}

func (m *defaultRpcUser) RateOrder(ctx context.Context, in *RateOrderReq, opts ...grpc.CallOption) (*RateOrderResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.RateOrder(ctx, in, opts...)
}

func (m *defaultRpcUser) GetWalletBalance(ctx context.Context, in *GetWalletBalanceReq, opts ...grpc.CallOption) (*GetWalletBalanceResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.GetWalletBalance(ctx, in, opts...)
}

func (m *defaultRpcUser) ListWalletLogs(ctx context.Context, in *ListWalletLogsReq, opts ...grpc.CallOption) (*ListWalletLogsResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.ListWalletLogs(ctx, in, opts...)
}

func (m *defaultRpcUser) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultRpcUser) GetOrderRating(ctx context.Context, in *GetOrderRatingReq, opts ...grpc.CallOption) (*GetOrderRatingResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.GetOrderRating(ctx, in, opts...)
}

func (m *defaultRpcUser) DeleteOrderRating(ctx context.Context, in *DeleteOrderRatingReq, opts ...grpc.CallOption) (*DeleteOrderRatingResp, error) {
	client := rpcUser.NewRpcUserClient(m.cli.Conn())
	return client.DeleteOrderRating(ctx, in, opts...)
}
