// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DriverLoginReq struct {
	Phone    string  `form:"phone"`
	Password string  `form:"password,optional"`
	Code     string  `form:"code,optional"`
	Type     int64   `form:"type"`
	Lng      float64 `form:"lng,optional"`
	Lat      float64 `form:"lat,optional"`
}

type DriverOfflineReq struct {
}

type DriverOrderListReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"page_size,optional"`
	OrderNo  string `form:"order_no,optional"`
	Status   int64  `form:"status,optional"` // 0全部 1待接单 2已接单 3已完成 4已取消 5用户已上车
}

type DriverOrderRatingReq struct {
	OrderNo string `form:"order_no"` // 订单号
}

type DriverRealNameReq struct {
	CardNo    string `form:"card_no"`
	RealName  string `form:"real_name"`
	Email     string `form:"email"`
	CarNumber string `form:"car_number"`
	CarType   string `form:"car_type"`
	CarColor  string `form:"car_color"`
}

type DriverRealNameStatusReq struct {
}

type DriverRegisterReq struct {
	Phone    string `form:"phone"`
	Password string `form:"password"`
	Code     string `form:"code"`
}

type DriverRpcTestReq struct {
	Msg string `form:"msg"`
}

type DriverSmsReq struct {
	Phone string `form:"phone"`
}

type DriverWalletBalanceReq struct {
}

type DriverWalletLogsReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"page_size,optional"`
	OrderNo  string `form:"order_no,optional"`
}

type MapChatReq struct {
	Question string `form:"question"` // 用户问题
	Type     int64  `form:"type"`     // 1=闲聊 2=业务助手
}

type MapGetCoordinatesReq struct {
	Address string `form:"address"` //地址
	Type    int64  `form:"type"`    //1用户 2司机
}

type MapIssueCouponsReq struct {
	Address   string  `form:"address"` // 目标地区地址，服务端转城市编码
	Type      int64   `form:"type"`    // 1现金券 2折扣券 3免费乘车券
	MoneyQuan float64 `form:"money_quan,optional"`
	Discount  float64 `form:"discount,optional"`
	OutTime   string  `form:"out_time"` // 2006-01-02 15:04:05
}

type MapReverseGeocodeReq struct {
	Lng float64 `form:"lng"`
	Lat float64 `form:"lat"`
}

type MapRpcTestReq struct {
	Msg string `form:"msg"`
}

type OrderCancelOrderReq struct {
	OrderNo string `form:"order_no"`        //订单号
	Reason  string `form:"reason,optional"` //取消原因
}

type OrderDriverOngoingReq struct {
}

type OrderGrabListReq struct {
	Radius int64 `form:"radius,optional"` //搜索半径(米)，默认5000
	Limit  int64 `form:"limit,optional"`  //返回条数，默认20
}

type OrderGrabOrderReq struct {
	OrderNo string `form:"order_no"` //订单号
}

type OrderJourneyReq struct {
	StartingPoint string `form:"starting_point"` //起点
	Destination   string `form:"destination"`    //终点
}

type OrderOverReq struct {
	OrderNo string `form:"order_no"` //订单号
}

type OrderRpcTestReq struct {
	Msg string `form:"msg"`
}

type OrderStartOrderReq struct {
	OrderNo   string `form:"order_no"`   //订单号
	PhoneTail string `form:"phone_tail"` //乘客手机号后四位
}

type OrderTakeCarReq struct {
	StartingPoint string `form:"starting_point"` //起点
	Destination   string `form:"destination"`    //终点
	Tid           int64  `form:"tid,optional"`   //优惠券id，0或不传表示不用
}

type OrderUserOngoingReq struct {
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UserAliPayBalanceReq struct {
	Money float64 `form:"money"` //充值金额
}

type UserListCouponsReq struct {
}

type UserLoginReq struct {
	Phone    string  `form:"phone"`
	Password string  `form:"password,optional"`
	Code     string  `form:"code,optional"`
	Type     int64   `form:"type"`
	Lng      float64 `form:"lng,optional"`
	Lat      float64 `form:"lat,optional"`
}

type UserOrderListReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"page_size,optional"`
	OrderNo  string `form:"order_no,optional"`
	Status   int64  `form:"status,optional"` // 0全部 1待接单 2已接单 3已完成 4已取消 5用户已上车
}

type UserOrderRatingReq struct {
	OrderNo string `form:"order_no"` // 订单号
}

type UserRateOrderReq struct {
	OrderNo string `form:"order_no"`         // 订单号
	Rating  int64  `form:"rating"`           // 1-5 星
	Comment string `form:"comment,optional"` // 评价内容
	Tags    string `form:"tags,optional"`    // 标签 JSON 数组，如 ["准时","服务好"]
}

type UserRealNameReq struct {
	CardNo   string `form:"card_no"`
	RealName string `form:"real_name"`
	Nickname string `form:"nickname,optional"`
	Gender   int64  `form:"gender,optional"`
	Email    string `form:"email,optional"`
}

type UserRealNameStatusReq struct {
}

type UserRegisterReq struct {
	Phone    string `form:"phone"`
	Password string `form:"password"`
	Code     string `form:"code"`
}

type UserRpcTestReq struct {
	Msg string `form:"msg"`
}

type UserSmsReq struct {
	Phone string `form:"phone"`
}

type UserWalletBalanceReq struct {
}

type UserWalletLogsReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"page_size,optional"`
	OrderNo  string `form:"order_no,optional"`
}
