// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpcDriver.proto

package rpcdriverclient

import (
	"context"

	"rpcDriver/rpcDriver"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DriverLoginReq        = rpcDriver.DriverLoginReq
	DriverLoginResp       = rpcDriver.DriverLoginResp
	DriverOfflineReq      = rpcDriver.DriverOfflineReq
	DriverOfflineResp     = rpcDriver.DriverOfflineResp
	DriverRegReq          = rpcDriver.DriverRegReq
	DriverRegResp         = rpcDriver.DriverRegResp
	DriverRpcTestReq      = rpcDriver.DriverRpcTestReq
	DriverRpcTestResp     = rpcDriver.DriverRpcTestResp
	GetOrderRatingReq     = rpcDriver.GetOrderRatingReq
	GetOrderRatingResp    = rpcDriver.GetOrderRatingResp
	GetRealNameStatusReq  = rpcDriver.GetRealNameStatusReq
	GetRealNameStatusResp = rpcDriver.GetRealNameStatusResp
	GetWalletBalanceReq   = rpcDriver.GetWalletBalanceReq
	GetWalletBalanceResp  = rpcDriver.GetWalletBalanceResp
	ListOrdersReq         = rpcDriver.ListOrdersReq
	ListOrdersResp        = rpcDriver.ListOrdersResp
	ListWalletLogsReq     = rpcDriver.ListWalletLogsReq
	ListWalletLogsResp    = rpcDriver.ListWalletLogsResp
	OrderListItem         = rpcDriver.OrderListItem
	RealNameReq           = rpcDriver.RealNameReq
	RealNameResp          = rpcDriver.RealNameResp
	Request               = rpcDriver.Request
	Response              = rpcDriver.Response
	SmsReq                = rpcDriver.SmsReq
	SmsResp               = rpcDriver.SmsResp
	WalletLogItem         = rpcDriver.WalletLogItem

	RpcDriver interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		DriverRpcTest(ctx context.Context, in *DriverRpcTestReq, opts ...grpc.CallOption) (*DriverRpcTestResp, error)
		Sms(ctx context.Context, in *SmsReq, opts ...grpc.CallOption) (*SmsResp, error)
		DriverReg(ctx context.Context, in *DriverRegReq, opts ...grpc.CallOption) (*DriverRegResp, error)
		DriverLogin(ctx context.Context, in *DriverLoginReq, opts ...grpc.CallOption) (*DriverLoginResp, error)
		RealName(ctx context.Context, in *RealNameReq, opts ...grpc.CallOption) (*RealNameResp, error)
		GetRealNameStatus(ctx context.Context, in *GetRealNameStatusReq, opts ...grpc.CallOption) (*GetRealNameStatusResp, error)
		Offline(ctx context.Context, in *DriverOfflineReq, opts ...grpc.CallOption) (*DriverOfflineResp, error)
		GetWalletBalance(ctx context.Context, in *GetWalletBalanceReq, opts ...grpc.CallOption) (*GetWalletBalanceResp, error)
		ListWalletLogs(ctx context.Context, in *ListWalletLogsReq, opts ...grpc.CallOption) (*ListWalletLogsResp, error)
		ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error)
		GetOrderRating(ctx context.Context, in *GetOrderRatingReq, opts ...grpc.CallOption) (*GetOrderRatingResp, error)
	}

	defaultRpcDriver struct {
		cli zrpc.Client
	}
)

func NewRpcDriver(cli zrpc.Client) RpcDriver {
	return &defaultRpcDriver{
		cli: cli,
	}
}

func (m *defaultRpcDriver) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultRpcDriver) DriverRpcTest(ctx context.Context, in *DriverRpcTestReq, opts ...grpc.CallOption) (*DriverRpcTestResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.DriverRpcTest(ctx, in, opts...)
}

func (m *defaultRpcDriver) Sms(ctx context.Context, in *SmsReq, opts ...grpc.CallOption) (*SmsResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.Sms(ctx, in, opts...)
}

func (m *defaultRpcDriver) DriverReg(ctx context.Context, in *DriverRegReq, opts ...grpc.CallOption) (*DriverRegResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.DriverReg(ctx, in, opts...)
}

func (m *defaultRpcDriver) DriverLogin(ctx context.Context, in *DriverLoginReq, opts ...grpc.CallOption) (*DriverLoginResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.DriverLogin(ctx, in, opts...)
}

func (m *defaultRpcDriver) RealName(ctx context.Context, in *RealNameReq, opts ...grpc.CallOption) (*RealNameResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.RealName(ctx, in, opts...)
}

func (m *defaultRpcDriver) GetRealNameStatus(ctx context.Context, in *GetRealNameStatusReq, opts ...grpc.CallOption) (*GetRealNameStatusResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.GetRealNameStatus(ctx, in, opts...)
}

func (m *defaultRpcDriver) Offline(ctx context.Context, in *DriverOfflineReq, opts ...grpc.CallOption) (*DriverOfflineResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.Offline(ctx, in, opts...)
}

func (m *defaultRpcDriver) GetWalletBalance(ctx context.Context, in *GetWalletBalanceReq, opts ...grpc.CallOption) (*GetWalletBalanceResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.GetWalletBalance(ctx, in, opts...)
}

func (m *defaultRpcDriver) ListWalletLogs(ctx context.Context, in *ListWalletLogsReq, opts ...grpc.CallOption) (*ListWalletLogsResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.ListWalletLogs(ctx, in, opts...)
}

func (m *defaultRpcDriver) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultRpcDriver) GetOrderRating(ctx context.Context, in *GetOrderRatingReq, opts ...grpc.CallOption) (*GetOrderRatingResp, error) {
	client := rpcDriver.NewRpcDriverClient(m.cli.Conn())
	return client.GetOrderRating(ctx, in, opts...)
}
