// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpcUser.proto

package rpcUser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_rpcUser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_rpcUser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type UserRpcTestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRpcTestReq) Reset() {
	*x = UserRpcTestReq{}
	mi := &file_rpcUser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRpcTestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRpcTestReq) ProtoMessage() {}

func (x *UserRpcTestReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRpcTestReq.ProtoReflect.Descriptor instead.
func (*UserRpcTestReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{2}
}

func (x *UserRpcTestReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UserRpcTestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRpcTestResp) Reset() {
	*x = UserRpcTestResp{}
	mi := &file_rpcUser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRpcTestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRpcTestResp) ProtoMessage() {}

func (x *UserRpcTestResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRpcTestResp.ProtoReflect.Descriptor instead.
func (*UserRpcTestResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{3}
}

func (x *UserRpcTestResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SmsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsReq) Reset() {
	*x = SmsReq{}
	mi := &file_rpcUser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsReq) ProtoMessage() {}

func (x *SmsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsReq.ProtoReflect.Descriptor instead.
func (*SmsReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{4}
}

func (x *SmsReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SmsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsResp) Reset() {
	*x = SmsResp{}
	mi := &file_rpcUser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsResp) ProtoMessage() {}

func (x *SmsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsResp.ProtoReflect.Descriptor instead.
func (*SmsResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{5}
}

func (x *SmsResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_rpcUser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_rpcUser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Type          int64                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Lng           float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat           float64                `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_rpcUser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{8}
}

func (x *LoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LoginReq) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *LoginReq) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_rpcUser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{9}
}

func (x *LoginResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RealNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CardNo        string                 `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int64                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameReq) Reset() {
	*x = RealNameReq{}
	mi := &file_rpcUser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameReq) ProtoMessage() {}

func (x *RealNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameReq.ProtoReflect.Descriptor instead.
func (*RealNameReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{10}
}

func (x *RealNameReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RealNameReq) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *RealNameReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *RealNameReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RealNameReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RealNameReq) GetGender() int64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *RealNameReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RealNameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameResp) Reset() {
	*x = RealNameResp{}
	mi := &file_rpcUser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameResp) ProtoMessage() {}

func (x *RealNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameResp.ProtoReflect.Descriptor instead.
func (*RealNameResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{11}
}

func (x *RealNameResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetRealNameStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealNameStatusReq) Reset() {
	*x = GetRealNameStatusReq{}
	mi := &file_rpcUser_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealNameStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealNameStatusReq) ProtoMessage() {}

func (x *GetRealNameStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealNameStatusReq.ProtoReflect.Descriptor instead.
func (*GetRealNameStatusReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{12}
}

func (x *GetRealNameStatusReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetRealNameStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"` // 是否已实名认证成功
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`     // 1正常 2未实名 3禁用
	StatusName    string                 `protobuf:"bytes,3,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	RealName      string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"` // 脱敏姓名，未认证为空
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealNameStatusResp) Reset() {
	*x = GetRealNameStatusResp{}
	mi := &file_rpcUser_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealNameStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealNameStatusResp) ProtoMessage() {}

func (x *GetRealNameStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealNameStatusResp.ProtoReflect.Descriptor instead.
func (*GetRealNameStatusResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{13}
}

func (x *GetRealNameStatusResp) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *GetRealNameStatusResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRealNameStatusResp) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *GetRealNameStatusResp) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *GetRealNameStatusResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetRealNameStatusResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type BalanceNotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          map[string]string      `protobuf:"bytes,1,rep,name=form,proto3" json:"form,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceNotifyReq) Reset() {
	*x = BalanceNotifyReq{}
	mi := &file_rpcUser_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceNotifyReq) ProtoMessage() {}

func (x *BalanceNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceNotifyReq.ProtoReflect.Descriptor instead.
func (*BalanceNotifyReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{14}
}

func (x *BalanceNotifyReq) GetForm() map[string]string {
	if x != nil {
		return x.Form
	}
	return nil
}

type BalanceNotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceNotifyResp) Reset() {
	*x = BalanceNotifyResp{}
	mi := &file_rpcUser_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceNotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceNotifyResp) ProtoMessage() {}

func (x *BalanceNotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceNotifyResp.ProtoReflect.Descriptor instead.
func (*BalanceNotifyResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{15}
}

func (x *BalanceNotifyResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type AliPayBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliPayBalanceReq) Reset() {
	*x = AliPayBalanceReq{}
	mi := &file_rpcUser_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliPayBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliPayBalanceReq) ProtoMessage() {}

func (x *AliPayBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliPayBalanceReq.ProtoReflect.Descriptor instead.
func (*AliPayBalanceReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{16}
}

func (x *AliPayBalanceReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AliPayBalanceReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type AliPayBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlipayUrl     string                 `protobuf:"bytes,1,opt,name=alipayUrl,proto3" json:"alipayUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliPayBalanceResp) Reset() {
	*x = AliPayBalanceResp{}
	mi := &file_rpcUser_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliPayBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliPayBalanceResp) ProtoMessage() {}

func (x *AliPayBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliPayBalanceResp.ProtoReflect.Descriptor instead.
func (*AliPayBalanceResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{17}
}

func (x *AliPayBalanceResp) GetAlipayUrl() string {
	if x != nil {
		return x.AlipayUrl
	}
	return ""
}

// ListCouponsReq 按用户 id 查询其全部优惠券
type ListCouponsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type          int64                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 已废弃，不再参与筛选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsReq) Reset() {
	*x = ListCouponsReq{}
	mi := &file_rpcUser_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsReq) ProtoMessage() {}

func (x *ListCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsReq.ProtoReflect.Descriptor instead.
func (*ListCouponsReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{18}
}

func (x *ListCouponsReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListCouponsReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CouponItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int64                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	MoneyQuan     float64                `protobuf:"fixed64,3,opt,name=money_quan,json=moneyQuan,proto3" json:"money_quan,omitempty"`
	Discount      float64                `protobuf:"fixed64,4,opt,name=discount,proto3" json:"discount,omitempty"`
	CityCode      string                 `protobuf:"bytes,5,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	OutTime       string                 `protobuf:"bytes,6,opt,name=out_time,json=outTime,proto3" json:"out_time,omitempty"`
	TypeName      string                 `protobuf:"bytes,7,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponItem) Reset() {
	*x = CouponItem{}
	mi := &file_rpcUser_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponItem) ProtoMessage() {}

func (x *CouponItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponItem.ProtoReflect.Descriptor instead.
func (*CouponItem) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{19}
}

func (x *CouponItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CouponItem) GetMoneyQuan() float64 {
	if x != nil {
		return x.MoneyQuan
	}
	return 0
}

func (x *CouponItem) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CouponItem) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *CouponItem) GetOutTime() string {
	if x != nil {
		return x.OutTime
	}
	return ""
}

func (x *CouponItem) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type ListCouponsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CouponItem          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsResp) Reset() {
	*x = ListCouponsResp{}
	mi := &file_rpcUser_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsResp) ProtoMessage() {}

func (x *ListCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsResp.ProtoReflect.Descriptor instead.
func (*ListCouponsResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{20}
}

func (x *ListCouponsResp) GetList() []*CouponItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListCouponsResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// RateOrderReq 乘客评价已完成订单
type RateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Rating        int64                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`  // 1-5 星
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"` // 评价内容，可选
	Tags          string                 `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`       // 标签 JSON 数组字符串，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateOrderReq) Reset() {
	*x = RateOrderReq{}
	mi := &file_rpcUser_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateOrderReq) ProtoMessage() {}

func (x *RateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateOrderReq.ProtoReflect.Descriptor instead.
func (*RateOrderReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{21}
}

func (x *RateOrderReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RateOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RateOrderReq) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RateOrderReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RateOrderReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type RateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	RatingId      int64                  `protobuf:"varint,2,opt,name=rating_id,json=ratingId,proto3" json:"rating_id,omitempty"`
	DriverRating  float64                `protobuf:"fixed64,3,opt,name=driver_rating,json=driverRating,proto3" json:"driver_rating,omitempty"` // 评价后司机最新平均分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateOrderResp) Reset() {
	*x = RateOrderResp{}
	mi := &file_rpcUser_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateOrderResp) ProtoMessage() {}

func (x *RateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateOrderResp.ProtoReflect.Descriptor instead.
func (*RateOrderResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{22}
}

func (x *RateOrderResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RateOrderResp) GetRatingId() int64 {
	if x != nil {
		return x.RatingId
	}
	return 0
}

func (x *RateOrderResp) GetDriverRating() float64 {
	if x != nil {
		return x.DriverRating
	}
	return 0
}

type GetWalletBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceReq) Reset() {
	*x = GetWalletBalanceReq{}
	mi := &file_rpcUser_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceReq) ProtoMessage() {}

func (x *GetWalletBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceReq.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{23}
}

func (x *GetWalletBalanceReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetWalletBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceResp) Reset() {
	*x = GetWalletBalanceResp{}
	mi := &file_rpcUser_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceResp) ProtoMessage() {}

func (x *GetWalletBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceResp.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{24}
}

func (x *GetWalletBalanceResp) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ListWalletLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletLogsReq) Reset() {
	*x = ListWalletLogsReq{}
	mi := &file_rpcUser_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletLogsReq) ProtoMessage() {}

func (x *ListWalletLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletLogsReq.ProtoReflect.Descriptor instead.
func (*ListWalletLogsReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{25}
}

func (x *ListWalletLogsReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListWalletLogsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWalletLogsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWalletLogsReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type WalletLogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	SignedAmount  float64                `protobuf:"fixed64,4,opt,name=signed_amount,json=signedAmount,proto3" json:"signed_amount,omitempty"`
	Direction     string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	BalanceBefore float64                `protobuf:"fixed64,6,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"`
	BalanceAfter  float64                `protobuf:"fixed64,7,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Type          int32                  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	TypeName      string                 `protobuf:"bytes,9,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	StatusName    string                 `protobuf:"bytes,11,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	Remark        string                 `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletLogItem) Reset() {
	*x = WalletLogItem{}
	mi := &file_rpcUser_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletLogItem) ProtoMessage() {}

func (x *WalletLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletLogItem.ProtoReflect.Descriptor instead.
func (*WalletLogItem) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{26}
}

func (x *WalletLogItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WalletLogItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *WalletLogItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WalletLogItem) GetSignedAmount() float64 {
	if x != nil {
		return x.SignedAmount
	}
	return 0
}

func (x *WalletLogItem) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *WalletLogItem) GetBalanceBefore() float64 {
	if x != nil {
		return x.BalanceBefore
	}
	return 0
}

func (x *WalletLogItem) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *WalletLogItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WalletLogItem) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *WalletLogItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WalletLogItem) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *WalletLogItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *WalletLogItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListWalletLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*WalletLogItem       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletLogsResp) Reset() {
	*x = ListWalletLogsResp{}
	mi := &file_rpcUser_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletLogsResp) ProtoMessage() {}

func (x *ListWalletLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletLogsResp.ProtoReflect.Descriptor instead.
func (*ListWalletLogsResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{27}
}

func (x *ListWalletLogsResp) GetList() []*WalletLogItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListWalletLogsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWalletLogsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWalletLogsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 0全部 1待接单 2已接单 3已完成 4已取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReq) Reset() {
	*x = ListOrdersReq{}
	mi := &file_rpcUser_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReq) ProtoMessage() {}

func (x *ListOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReq.ProtoReflect.Descriptor instead.
func (*ListOrdersReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{28}
}

func (x *ListOrdersReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListOrdersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ListOrdersReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OrderListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartAddress  string                 `protobuf:"bytes,5,opt,name=start_address,json=startAddress,proto3" json:"start_address,omitempty"`
	EndAddress    string                 `protobuf:"bytes,6,opt,name=end_address,json=endAddress,proto3" json:"end_address,omitempty"`
	Distance      float64                `protobuf:"fixed64,7,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      int64                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Price         float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	PayType       int32                  `protobuf:"varint,10,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	StatusName    string                 `protobuf:"bytes,12,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	CancelReason  string                 `protobuf:"bytes,13,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	AcceptTime    string                 `protobuf:"bytes,14,opt,name=accept_time,json=acceptTime,proto3" json:"accept_time,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListItem) Reset() {
	*x = OrderListItem{}
	mi := &file_rpcUser_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListItem) ProtoMessage() {}

func (x *OrderListItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListItem.ProtoReflect.Descriptor instead.
func (*OrderListItem) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{29}
}

func (x *OrderListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderListItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderListItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderListItem) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *OrderListItem) GetStartAddress() string {
	if x != nil {
		return x.StartAddress
	}
	return ""
}

func (x *OrderListItem) GetEndAddress() string {
	if x != nil {
		return x.EndAddress
	}
	return ""
}

func (x *OrderListItem) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *OrderListItem) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *OrderListItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderListItem) GetPayType() int32 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *OrderListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderListItem) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *OrderListItem) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *OrderListItem) GetAcceptTime() string {
	if x != nil {
		return x.AcceptTime
	}
	return ""
}

func (x *OrderListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderListItem       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResp) Reset() {
	*x = ListOrdersResp{}
	mi := &file_rpcUser_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResp) ProtoMessage() {}

func (x *ListOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResp.ProtoReflect.Descriptor instead.
func (*ListOrdersResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{30}
}

func (x *ListOrdersResp) GetList() []*OrderListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListOrdersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetOrderRatingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRatingReq) Reset() {
	*x = GetOrderRatingReq{}
	mi := &file_rpcUser_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRatingReq) ProtoMessage() {}

func (x *GetOrderRatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRatingReq.ProtoReflect.Descriptor instead.
func (*GetOrderRatingReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{31}
}

func (x *GetOrderRatingReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetOrderRatingReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetOrderRatingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Rating        int64                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Tags          string                 `protobuf:"bytes,7,opt,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRatingResp) Reset() {
	*x = GetOrderRatingResp{}
	mi := &file_rpcUser_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRatingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRatingResp) ProtoMessage() {}

func (x *GetOrderRatingResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRatingResp.ProtoReflect.Descriptor instead.
func (*GetOrderRatingResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{32}
}

func (x *GetOrderRatingResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderRatingResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrderRatingResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderRatingResp) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *GetOrderRatingResp) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetOrderRatingResp) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetOrderRatingResp) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GetOrderRatingResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DeleteOrderRatingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRatingReq) Reset() {
	*x = DeleteOrderRatingReq{}
	mi := &file_rpcUser_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRatingReq) ProtoMessage() {}

func (x *DeleteOrderRatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRatingReq.ProtoReflect.Descriptor instead.
func (*DeleteOrderRatingReq) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteOrderRatingReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DeleteOrderRatingReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type DeleteOrderRatingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	DriverRating  float64                `protobuf:"fixed64,2,opt,name=driver_rating,json=driverRating,proto3" json:"driver_rating,omitempty"` // 删除后司机最新平均分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRatingResp) Reset() {
	*x = DeleteOrderRatingResp{}
	mi := &file_rpcUser_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRatingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRatingResp) ProtoMessage() {}

func (x *DeleteOrderRatingResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcUser_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRatingResp.ProtoReflect.Descriptor instead.
func (*DeleteOrderRatingResp) Descriptor() ([]byte, []int) {
	return file_rpcUser_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteOrderRatingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DeleteOrderRatingResp) GetDriverRating() float64 {
	if x != nil {
		return x.DriverRating
	}
	return 0
}

var File_rpcUser_proto protoreflect.FileDescriptor

const file_rpcUser_proto_rawDesc = "" +
	"\n" +
	"\rrpcUser.proto\x12\arpcUser\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\"\n" +
	"\x0eUserRpcTestReq\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\")\n" +
	"\x0fUserRpcTestResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x1e\n" +
	"\x06SmsReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"!\n" +
	"\aSmsResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"S\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"\x1e\n" +
	"\fRegisterResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x88\x01\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\x01R\x03lat\"\x1b\n" +
	"\tLoginResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb7\x01\n" +
	"\vRealNameReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\acard_no\x18\x02 \x01(\tR\x06cardNo\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x03R\x06gender\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\" \n" +
	"\fRealNameResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"(\n" +
	"\x14GetRealNameStatusReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"\xbd\x01\n" +
	"\x15GetRealNameStatusResp\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\x03 \x01(\tR\n" +
	"statusName\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\"\x84\x01\n" +
	"\x10BalanceNotifyReq\x127\n" +
	"\x04form\x18\x01 \x03(\v2#.rpcUser.BalanceNotifyReq.FormEntryR\x04form\x1a7\n" +
	"\tFormEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x11BalanceNotifyResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\":\n" +
	"\x10AliPayBalanceReq\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"1\n" +
	"\x11AliPayBalanceResp\x12\x1c\n" +
	"\talipayUrl\x18\x01 \x01(\tR\talipayUrl\"6\n" +
	"\x0eListCouponsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x03R\x04type\"\xc0\x01\n" +
	"\n" +
	"CouponItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x03R\x04type\x12\x1d\n" +
	"\n" +
	"money_quan\x18\x03 \x01(\x01R\tmoneyQuan\x12\x1a\n" +
	"\bdiscount\x18\x04 \x01(\x01R\bdiscount\x12\x1b\n" +
	"\tcity_code\x18\x05 \x01(\tR\bcityCode\x12\x19\n" +
	"\bout_time\x18\x06 \x01(\tR\aoutTime\x12\x1b\n" +
	"\ttype_name\x18\a \x01(\tR\btypeName\"P\n" +
	"\x0fListCouponsResp\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.rpcUser.CouponItemR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x81\x01\n" +
	"\fRateOrderReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x03R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\tR\x04tags\"c\n" +
	"\rRateOrderResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1b\n" +
	"\trating_id\x18\x02 \x01(\x03R\bratingId\x12#\n" +
	"\rdriver_rating\x18\x03 \x01(\x01R\fdriverRating\"'\n" +
	"\x13GetWalletBalanceReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"0\n" +
	"\x14GetWalletBalanceResp\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\"q\n" +
	"\x11ListWalletLogsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\"\x82\x03\n" +
	"\rWalletLogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12#\n" +
	"\rsigned_amount\x18\x04 \x01(\x01R\fsignedAmount\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x12%\n" +
	"\x0ebalance_before\x18\x06 \x01(\x01R\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\a \x01(\x01R\fbalanceAfter\x12\x12\n" +
	"\x04type\x18\b \x01(\x05R\x04type\x12\x1b\n" +
	"\ttype_name\x18\t \x01(\tR\btypeName\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\v \x01(\tR\n" +
	"statusName\x12\x16\n" +
	"\x06remark\x18\f \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\"\x87\x01\n" +
	"\x12ListWalletLogsResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.rpcUser.WalletLogItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x85\x01\n" +
	"\rListOrdersReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\xbd\x03\n" +
	"\rOrderListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x03R\bdriverId\x12#\n" +
	"\rstart_address\x18\x05 \x01(\tR\fstartAddress\x12\x1f\n" +
	"\vend_address\x18\x06 \x01(\tR\n" +
	"endAddress\x12\x1a\n" +
	"\bdistance\x18\a \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\b \x01(\x03R\bduration\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12\x19\n" +
	"\bpay_type\x18\n" +
	" \x01(\x05R\apayType\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\f \x01(\tR\n" +
	"statusName\x12#\n" +
	"\rcancel_reason\x18\r \x01(\tR\fcancelReason\x12\x1f\n" +
	"\vaccept_time\x18\x0e \x01(\tR\n" +
	"acceptTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\"\x83\x01\n" +
	"\x0eListOrdersResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.rpcUser.OrderListItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"@\n" +
	"\x11GetOrderRatingReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"\xda\x01\n" +
	"\x12GetOrderRatingResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x03R\bdriverId\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x03R\x06rating\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x12\n" +
	"\x04tags\x18\a \x01(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"C\n" +
	"\x14DeleteOrderRatingReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"N\n" +
	"\x15DeleteOrderRatingResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12#\n" +
	"\rdriver_rating\x18\x02 \x01(\x01R\fdriverRating2\xa0\b\n" +
	"\aRpcUser\x12+\n" +
	"\x04Ping\x12\x10.rpcUser.Request\x1a\x11.rpcUser.Response\x12@\n" +
	"\vUserRpcTest\x12\x17.rpcUser.UserRpcTestReq\x1a\x18.rpcUser.UserRpcTestResp\x12(\n" +
	"\x03Sms\x12\x0f.rpcUser.SmsReq\x1a\x10.rpcUser.SmsResp\x127\n" +
	"\bRegister\x12\x14.rpcUser.RegisterReq\x1a\x15.rpcUser.RegisterResp\x12.\n" +
	"\x05Login\x12\x11.rpcUser.LoginReq\x1a\x12.rpcUser.LoginResp\x127\n" +
	"\bRealName\x12\x14.rpcUser.RealNameReq\x1a\x15.rpcUser.RealNameResp\x12R\n" +
	"\x11GetRealNameStatus\x12\x1d.rpcUser.GetRealNameStatusReq\x1a\x1e.rpcUser.GetRealNameStatusResp\x12F\n" +
	"\rBalanceNotify\x12\x19.rpcUser.BalanceNotifyReq\x1a\x1a.rpcUser.BalanceNotifyResp\x12F\n" +
	"\rAliPayBalance\x12\x19.rpcUser.AliPayBalanceReq\x1a\x1a.rpcUser.AliPayBalanceResp\x12@\n" +
	"\vListCoupons\x12\x17.rpcUser.ListCouponsReq\x1a\x18.rpcUser.ListCouponsResp\x12:\n" +
	"\tRateOrder\x12\x15.rpcUser.RateOrderReq\x1a\x16.rpcUser.RateOrderResp\x12O\n" +
	"\x10GetWalletBalance\x12\x1c.rpcUser.GetWalletBalanceReq\x1a\x1d.rpcUser.GetWalletBalanceResp\x12I\n" +
	"\x0eListWalletLogs\x12\x1a.rpcUser.ListWalletLogsReq\x1a\x1b.rpcUser.ListWalletLogsResp\x12=\n" +
	"\n" +
	"ListOrders\x12\x16.rpcUser.ListOrdersReq\x1a\x17.rpcUser.ListOrdersResp\x12I\n" +
	"\x0eGetOrderRating\x12\x1a.rpcUser.GetOrderRatingReq\x1a\x1b.rpcUser.GetOrderRatingResp\x12R\n" +
	"\x11DeleteOrderRating\x12\x1d.rpcUser.DeleteOrderRatingReq\x1a\x1e.rpcUser.DeleteOrderRatingRespB\vZ\t./rpcUserb\x06proto3"

var (
	file_rpcUser_proto_rawDescOnce sync.Once
	file_rpcUser_proto_rawDescData []byte
)

func file_rpcUser_proto_rawDescGZIP() []byte {
	file_rpcUser_proto_rawDescOnce.Do(func() {
		file_rpcUser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcUser_proto_rawDesc), len(file_rpcUser_proto_rawDesc)))
	})
	return file_rpcUser_proto_rawDescData
}

var file_rpcUser_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_rpcUser_proto_goTypes = []any{
	(*Request)(nil),               // 0: rpcUser.Request
	(*Response)(nil),              // 1: rpcUser.Response
	(*UserRpcTestReq)(nil),        // 2: rpcUser.UserRpcTestReq
	(*UserRpcTestResp)(nil),       // 3: rpcUser.UserRpcTestResp
	(*SmsReq)(nil),                // 4: rpcUser.SmsReq
	(*SmsResp)(nil),               // 5: rpcUser.SmsResp
	(*RegisterReq)(nil),           // 6: rpcUser.RegisterReq
	(*RegisterResp)(nil),          // 7: rpcUser.RegisterResp
	(*LoginReq)(nil),              // 8: rpcUser.LoginReq
	(*LoginResp)(nil),             // 9: rpcUser.LoginResp
	(*RealNameReq)(nil),           // 10: rpcUser.RealNameReq
	(*RealNameResp)(nil),          // 11: rpcUser.RealNameResp
	(*GetRealNameStatusReq)(nil),  // 12: rpcUser.GetRealNameStatusReq
	(*GetRealNameStatusResp)(nil), // 13: rpcUser.GetRealNameStatusResp
	(*BalanceNotifyReq)(nil),      // 14: rpcUser.BalanceNotifyReq
	(*BalanceNotifyResp)(nil),     // 15: rpcUser.BalanceNotifyResp
	(*AliPayBalanceReq)(nil),      // 16: rpcUser.AliPayBalanceReq
	(*AliPayBalanceResp)(nil),     // 17: rpcUser.AliPayBalanceResp
	(*ListCouponsReq)(nil),        // 18: rpcUser.ListCouponsReq
	(*CouponItem)(nil),            // 19: rpcUser.CouponItem
	(*ListCouponsResp)(nil),       // 20: rpcUser.ListCouponsResp
	(*RateOrderReq)(nil),          // 21: rpcUser.RateOrderReq
	(*RateOrderResp)(nil),         // 22: rpcUser.RateOrderResp
	(*GetWalletBalanceReq)(nil),   // 23: rpcUser.GetWalletBalanceReq
	(*GetWalletBalanceResp)(nil),  // 24: rpcUser.GetWalletBalanceResp
	(*ListWalletLogsReq)(nil),     // 25: rpcUser.ListWalletLogsReq
	(*WalletLogItem)(nil),         // 26: rpcUser.WalletLogItem
	(*ListWalletLogsResp)(nil),    // 27: rpcUser.ListWalletLogsResp
	(*ListOrdersReq)(nil),         // 28: rpcUser.ListOrdersReq
	(*OrderListItem)(nil),         // 29: rpcUser.OrderListItem
	(*ListOrdersResp)(nil),        // 30: rpcUser.ListOrdersResp
	(*GetOrderRatingReq)(nil),     // 31: rpcUser.GetOrderRatingReq
	(*GetOrderRatingResp)(nil),    // 32: rpcUser.GetOrderRatingResp
	(*DeleteOrderRatingReq)(nil),  // 33: rpcUser.DeleteOrderRatingReq
	(*DeleteOrderRatingResp)(nil), // 34: rpcUser.DeleteOrderRatingResp
	nil,                           // 35: rpcUser.BalanceNotifyReq.FormEntry
}
var file_rpcUser_proto_depIdxs = []int32{
	35, // 0: rpcUser.BalanceNotifyReq.form:type_name -> rpcUser.BalanceNotifyReq.FormEntry
	19, // 1: rpcUser.ListCouponsResp.list:type_name -> rpcUser.CouponItem
	26, // 2: rpcUser.ListWalletLogsResp.list:type_name -> rpcUser.WalletLogItem
	29, // 3: rpcUser.ListOrdersResp.list:type_name -> rpcUser.OrderListItem
	0,  // 4: rpcUser.RpcUser.Ping:input_type -> rpcUser.Request
	2,  // 5: rpcUser.RpcUser.UserRpcTest:input_type -> rpcUser.UserRpcTestReq
	4,  // 6: rpcUser.RpcUser.Sms:input_type -> rpcUser.SmsReq
	6,  // 7: rpcUser.RpcUser.Register:input_type -> rpcUser.RegisterReq
	8,  // 8: rpcUser.RpcUser.Login:input_type -> rpcUser.LoginReq
	10, // 9: rpcUser.RpcUser.RealName:input_type -> rpcUser.RealNameReq
	12, // 10: rpcUser.RpcUser.GetRealNameStatus:input_type -> rpcUser.GetRealNameStatusReq
	14, // 11: rpcUser.RpcUser.BalanceNotify:input_type -> rpcUser.BalanceNotifyReq
	16, // 12: rpcUser.RpcUser.AliPayBalance:input_type -> rpcUser.AliPayBalanceReq
	18, // 13: rpcUser.RpcUser.ListCoupons:input_type -> rpcUser.ListCouponsReq
	21, // 14: rpcUser.RpcUser.RateOrder:input_type -> rpcUser.RateOrderReq
	23, // 15: rpcUser.RpcUser.GetWalletBalance:input_type -> rpcUser.GetWalletBalanceReq
	25, // 16: rpcUser.RpcUser.ListWalletLogs:input_type -> rpcUser.ListWalletLogsReq
	28, // 17: rpcUser.RpcUser.ListOrders:input_type -> rpcUser.ListOrdersReq
	31, // 18: rpcUser.RpcUser.GetOrderRating:input_type -> rpcUser.GetOrderRatingReq
	33, // 19: rpcUser.RpcUser.DeleteOrderRating:input_type -> rpcUser.DeleteOrderRatingReq
	1,  // 20: rpcUser.RpcUser.Ping:output_type -> rpcUser.Response
	3,  // 21: rpcUser.RpcUser.UserRpcTest:output_type -> rpcUser.UserRpcTestResp
	5,  // 22: rpcUser.RpcUser.Sms:output_type -> rpcUser.SmsResp
	7,  // 23: rpcUser.RpcUser.Register:output_type -> rpcUser.RegisterResp
	9,  // 24: rpcUser.RpcUser.Login:output_type -> rpcUser.LoginResp
	11, // 25: rpcUser.RpcUser.RealName:output_type -> rpcUser.RealNameResp
	13, // 26: rpcUser.RpcUser.GetRealNameStatus:output_type -> rpcUser.GetRealNameStatusResp
	15, // 27: rpcUser.RpcUser.BalanceNotify:output_type -> rpcUser.BalanceNotifyResp
	17, // 28: rpcUser.RpcUser.AliPayBalance:output_type -> rpcUser.AliPayBalanceResp
	20, // 29: rpcUser.RpcUser.ListCoupons:output_type -> rpcUser.ListCouponsResp
	22, // 30: rpcUser.RpcUser.RateOrder:output_type -> rpcUser.RateOrderResp
	24, // 31: rpcUser.RpcUser.GetWalletBalance:output_type -> rpcUser.GetWalletBalanceResp
	27, // 32: rpcUser.RpcUser.ListWalletLogs:output_type -> rpcUser.ListWalletLogsResp
	30, // 33: rpcUser.RpcUser.ListOrders:output_type -> rpcUser.ListOrdersResp
	32, // 34: rpcUser.RpcUser.GetOrderRating:output_type -> rpcUser.GetOrderRatingResp
	34, // 35: rpcUser.RpcUser.DeleteOrderRating:output_type -> rpcUser.DeleteOrderRatingResp
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpcUser_proto_init() }
func file_rpcUser_proto_init() {
	if File_rpcUser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcUser_proto_rawDesc), len(file_rpcUser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcUser_proto_goTypes,
		DependencyIndexes: file_rpcUser_proto_depIdxs,
		MessageInfos:      file_rpcUser_proto_msgTypes,
	}.Build()
	File_rpcUser_proto = out.File
	file_rpcUser_proto_goTypes = nil
	file_rpcUser_proto_depIdxs = nil
}
