// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: rpcUser.proto

package rpcUser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcUser_Ping_FullMethodName              = "/rpcUser.RpcUser/Ping"
	RpcUser_UserRpcTest_FullMethodName       = "/rpcUser.RpcUser/UserRpcTest"
	RpcUser_Sms_FullMethodName               = "/rpcUser.RpcUser/Sms"
	RpcUser_Register_FullMethodName          = "/rpcUser.RpcUser/Register"
	RpcUser_Login_FullMethodName             = "/rpcUser.RpcUser/Login"
	RpcUser_RealName_FullMethodName          = "/rpcUser.RpcUser/RealName"
	RpcUser_GetRealNameStatus_FullMethodName = "/rpcUser.RpcUser/GetRealNameStatus"
	RpcUser_BalanceNotify_FullMethodName     = "/rpcUser.RpcUser/BalanceNotify"
	RpcUser_AliPayBalance_FullMethodName     = "/rpcUser.RpcUser/AliPayBalance"
	RpcUser_ListCoupons_FullMethodName       = "/rpcUser.RpcUser/ListCoupons"
	RpcUser_RateOrder_FullMethodName         = "/rpcUser.RpcUser/RateOrder"
	RpcUser_GetWalletBalance_FullMethodName  = "/rpcUser.RpcUser/GetWalletBalance"
	RpcUser_ListWalletLogs_FullMethodName    = "/rpcUser.RpcUser/ListWalletLogs"
	RpcUser_ListOrders_FullMethodName        = "/rpcUser.RpcUser/ListOrders"
	RpcUser_GetOrderRating_FullMethodName    = "/rpcUser.RpcUser/GetOrderRating"
	RpcUser_DeleteOrderRating_FullMethodName = "/rpcUser.RpcUser/DeleteOrderRating"
)

// RpcUserClient is the client API for RpcUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcUserClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	UserRpcTest(ctx context.Context, in *UserRpcTestReq, opts ...grpc.CallOption) (*UserRpcTestResp, error)
	Sms(ctx context.Context, in *SmsReq, opts ...grpc.CallOption) (*SmsResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	RealName(ctx context.Context, in *RealNameReq, opts ...grpc.CallOption) (*RealNameResp, error)
	GetRealNameStatus(ctx context.Context, in *GetRealNameStatusReq, opts ...grpc.CallOption) (*GetRealNameStatusResp, error)
	BalanceNotify(ctx context.Context, in *BalanceNotifyReq, opts ...grpc.CallOption) (*BalanceNotifyResp, error)
	AliPayBalance(ctx context.Context, in *AliPayBalanceReq, opts ...grpc.CallOption) (*AliPayBalanceResp, error)
	ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error)
	RateOrder(ctx context.Context, in *RateOrderReq, opts ...grpc.CallOption) (*RateOrderResp, error)
	GetWalletBalance(ctx context.Context, in *GetWalletBalanceReq, opts ...grpc.CallOption) (*GetWalletBalanceResp, error)
	ListWalletLogs(ctx context.Context, in *ListWalletLogsReq, opts ...grpc.CallOption) (*ListWalletLogsResp, error)
	ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error)
	GetOrderRating(ctx context.Context, in *GetOrderRatingReq, opts ...grpc.CallOption) (*GetOrderRatingResp, error)
	DeleteOrderRating(ctx context.Context, in *DeleteOrderRatingReq, opts ...grpc.CallOption) (*DeleteOrderRatingResp, error)
}

type rpcUserClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcUserClient(cc grpc.ClientConnInterface) RpcUserClient {
	return &rpcUserClient{cc}
}

func (c *rpcUserClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RpcUser_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) UserRpcTest(ctx context.Context, in *UserRpcTestReq, opts ...grpc.CallOption) (*UserRpcTestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRpcTestResp)
	err := c.cc.Invoke(ctx, RpcUser_UserRpcTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) Sms(ctx context.Context, in *SmsReq, opts ...grpc.CallOption) (*SmsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmsResp)
	err := c.cc.Invoke(ctx, RpcUser_Sms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, RpcUser_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, RpcUser_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) RealName(ctx context.Context, in *RealNameReq, opts ...grpc.CallOption) (*RealNameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealNameResp)
	err := c.cc.Invoke(ctx, RpcUser_RealName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) GetRealNameStatus(ctx context.Context, in *GetRealNameStatusReq, opts ...grpc.CallOption) (*GetRealNameStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRealNameStatusResp)
	err := c.cc.Invoke(ctx, RpcUser_GetRealNameStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) BalanceNotify(ctx context.Context, in *BalanceNotifyReq, opts ...grpc.CallOption) (*BalanceNotifyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceNotifyResp)
	err := c.cc.Invoke(ctx, RpcUser_BalanceNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) AliPayBalance(ctx context.Context, in *AliPayBalanceReq, opts ...grpc.CallOption) (*AliPayBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliPayBalanceResp)
	err := c.cc.Invoke(ctx, RpcUser_AliPayBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponsResp)
	err := c.cc.Invoke(ctx, RpcUser_ListCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) RateOrder(ctx context.Context, in *RateOrderReq, opts ...grpc.CallOption) (*RateOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateOrderResp)
	err := c.cc.Invoke(ctx, RpcUser_RateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) GetWalletBalance(ctx context.Context, in *GetWalletBalanceReq, opts ...grpc.CallOption) (*GetWalletBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletBalanceResp)
	err := c.cc.Invoke(ctx, RpcUser_GetWalletBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) ListWalletLogs(ctx context.Context, in *ListWalletLogsReq, opts ...grpc.CallOption) (*ListWalletLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletLogsResp)
	err := c.cc.Invoke(ctx, RpcUser_ListWalletLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResp)
	err := c.cc.Invoke(ctx, RpcUser_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) GetOrderRating(ctx context.Context, in *GetOrderRatingReq, opts ...grpc.CallOption) (*GetOrderRatingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderRatingResp)
	err := c.cc.Invoke(ctx, RpcUser_GetOrderRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcUserClient) DeleteOrderRating(ctx context.Context, in *DeleteOrderRatingReq, opts ...grpc.CallOption) (*DeleteOrderRatingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOrderRatingResp)
	err := c.cc.Invoke(ctx, RpcUser_DeleteOrderRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcUserServer is the server API for RpcUser service.
// All implementations must embed UnimplementedRpcUserServer
// for forward compatibility.
type RpcUserServer interface {
	Ping(context.Context, *Request) (*Response, error)
	UserRpcTest(context.Context, *UserRpcTestReq) (*UserRpcTestResp, error)
	Sms(context.Context, *SmsReq) (*SmsResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	RealName(context.Context, *RealNameReq) (*RealNameResp, error)
	GetRealNameStatus(context.Context, *GetRealNameStatusReq) (*GetRealNameStatusResp, error)
	BalanceNotify(context.Context, *BalanceNotifyReq) (*BalanceNotifyResp, error)
	AliPayBalance(context.Context, *AliPayBalanceReq) (*AliPayBalanceResp, error)
	ListCoupons(context.Context, *ListCouponsReq) (*ListCouponsResp, error)
	RateOrder(context.Context, *RateOrderReq) (*RateOrderResp, error)
	GetWalletBalance(context.Context, *GetWalletBalanceReq) (*GetWalletBalanceResp, error)
	ListWalletLogs(context.Context, *ListWalletLogsReq) (*ListWalletLogsResp, error)
	ListOrders(context.Context, *ListOrdersReq) (*ListOrdersResp, error)
	GetOrderRating(context.Context, *GetOrderRatingReq) (*GetOrderRatingResp, error)
	DeleteOrderRating(context.Context, *DeleteOrderRatingReq) (*DeleteOrderRatingResp, error)
	mustEmbedUnimplementedRpcUserServer()
}

// UnimplementedRpcUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcUserServer struct{}

func (UnimplementedRpcUserServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcUserServer) UserRpcTest(context.Context, *UserRpcTestReq) (*UserRpcTestResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserRpcTest not implemented")
}
func (UnimplementedRpcUserServer) Sms(context.Context, *SmsReq) (*SmsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Sms not implemented")
}
func (UnimplementedRpcUserServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRpcUserServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedRpcUserServer) RealName(context.Context, *RealNameReq) (*RealNameResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RealName not implemented")
}
func (UnimplementedRpcUserServer) GetRealNameStatus(context.Context, *GetRealNameStatusReq) (*GetRealNameStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRealNameStatus not implemented")
}
func (UnimplementedRpcUserServer) BalanceNotify(context.Context, *BalanceNotifyReq) (*BalanceNotifyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BalanceNotify not implemented")
}
func (UnimplementedRpcUserServer) AliPayBalance(context.Context, *AliPayBalanceReq) (*AliPayBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AliPayBalance not implemented")
}
func (UnimplementedRpcUserServer) ListCoupons(context.Context, *ListCouponsReq) (*ListCouponsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCoupons not implemented")
}
func (UnimplementedRpcUserServer) RateOrder(context.Context, *RateOrderReq) (*RateOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RateOrder not implemented")
}
func (UnimplementedRpcUserServer) GetWalletBalance(context.Context, *GetWalletBalanceReq) (*GetWalletBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletBalance not implemented")
}
func (UnimplementedRpcUserServer) ListWalletLogs(context.Context, *ListWalletLogsReq) (*ListWalletLogsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWalletLogs not implemented")
}
func (UnimplementedRpcUserServer) ListOrders(context.Context, *ListOrdersReq) (*ListOrdersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedRpcUserServer) GetOrderRating(context.Context, *GetOrderRatingReq) (*GetOrderRatingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderRating not implemented")
}
func (UnimplementedRpcUserServer) DeleteOrderRating(context.Context, *DeleteOrderRatingReq) (*DeleteOrderRatingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrderRating not implemented")
}
func (UnimplementedRpcUserServer) mustEmbedUnimplementedRpcUserServer() {}
func (UnimplementedRpcUserServer) testEmbeddedByValue()                 {}

// UnsafeRpcUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcUserServer will
// result in compilation errors.
type UnsafeRpcUserServer interface {
	mustEmbedUnimplementedRpcUserServer()
}

func RegisterRpcUserServer(s grpc.ServiceRegistrar, srv RpcUserServer) {
	// If the following call panics, it indicates UnimplementedRpcUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcUser_ServiceDesc, srv)
}

func _RpcUser_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_UserRpcTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRpcTestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).UserRpcTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_UserRpcTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).UserRpcTest(ctx, req.(*UserRpcTestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_Sms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).Sms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_Sms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).Sms(ctx, req.(*SmsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_RealName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).RealName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_RealName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).RealName(ctx, req.(*RealNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_GetRealNameStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRealNameStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).GetRealNameStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_GetRealNameStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).GetRealNameStatus(ctx, req.(*GetRealNameStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_BalanceNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).BalanceNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_BalanceNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).BalanceNotify(ctx, req.(*BalanceNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_AliPayBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliPayBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).AliPayBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_AliPayBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).AliPayBalance(ctx, req.(*AliPayBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_ListCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).ListCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_ListCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).ListCoupons(ctx, req.(*ListCouponsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_RateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).RateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_RateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).RateOrder(ctx, req.(*RateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_GetWalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).GetWalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_GetWalletBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).GetWalletBalance(ctx, req.(*GetWalletBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_ListWalletLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).ListWalletLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_ListWalletLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).ListWalletLogs(ctx, req.(*ListWalletLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).ListOrders(ctx, req.(*ListOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_GetOrderRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRatingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).GetOrderRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_GetOrderRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).GetOrderRating(ctx, req.(*GetOrderRatingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcUser_DeleteOrderRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderRatingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServer).DeleteOrderRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcUser_DeleteOrderRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServer).DeleteOrderRating(ctx, req.(*DeleteOrderRatingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcUser_ServiceDesc is the grpc.ServiceDesc for RpcUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcUser.RpcUser",
	HandlerType: (*RpcUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RpcUser_Ping_Handler,
		},
		{
			MethodName: "UserRpcTest",
			Handler:    _RpcUser_UserRpcTest_Handler,
		},
		{
			MethodName: "Sms",
			Handler:    _RpcUser_Sms_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _RpcUser_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _RpcUser_Login_Handler,
		},
		{
			MethodName: "RealName",
			Handler:    _RpcUser_RealName_Handler,
		},
		{
			MethodName: "GetRealNameStatus",
			Handler:    _RpcUser_GetRealNameStatus_Handler,
		},
		{
			MethodName: "BalanceNotify",
			Handler:    _RpcUser_BalanceNotify_Handler,
		},
		{
			MethodName: "AliPayBalance",
			Handler:    _RpcUser_AliPayBalance_Handler,
		},
		{
			MethodName: "ListCoupons",
			Handler:    _RpcUser_ListCoupons_Handler,
		},
		{
			MethodName: "RateOrder",
			Handler:    _RpcUser_RateOrder_Handler,
		},
		{
			MethodName: "GetWalletBalance",
			Handler:    _RpcUser_GetWalletBalance_Handler,
		},
		{
			MethodName: "ListWalletLogs",
			Handler:    _RpcUser_ListWalletLogs_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _RpcUser_ListOrders_Handler,
		},
		{
			MethodName: "GetOrderRating",
			Handler:    _RpcUser_GetOrderRating_Handler,
		},
		{
			MethodName: "DeleteOrderRating",
			Handler:    _RpcUser_DeleteOrderRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcUser.proto",
}
