// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: rpcDriver.proto

package rpcDriver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcDriver_Ping_FullMethodName              = "/rpcDriver.RpcDriver/Ping"
	RpcDriver_DriverRpcTest_FullMethodName     = "/rpcDriver.RpcDriver/DriverRpcTest"
	RpcDriver_Sms_FullMethodName               = "/rpcDriver.RpcDriver/Sms"
	RpcDriver_DriverReg_FullMethodName         = "/rpcDriver.RpcDriver/DriverReg"
	RpcDriver_DriverLogin_FullMethodName       = "/rpcDriver.RpcDriver/DriverLogin"
	RpcDriver_RealName_FullMethodName          = "/rpcDriver.RpcDriver/RealName"
	RpcDriver_GetRealNameStatus_FullMethodName = "/rpcDriver.RpcDriver/GetRealNameStatus"
	RpcDriver_Offline_FullMethodName           = "/rpcDriver.RpcDriver/Offline"
	RpcDriver_GetWalletBalance_FullMethodName  = "/rpcDriver.RpcDriver/GetWalletBalance"
	RpcDriver_ListWalletLogs_FullMethodName    = "/rpcDriver.RpcDriver/ListWalletLogs"
	RpcDriver_ListOrders_FullMethodName        = "/rpcDriver.RpcDriver/ListOrders"
	RpcDriver_GetOrderRating_FullMethodName    = "/rpcDriver.RpcDriver/GetOrderRating"
)

// RpcDriverClient is the client API for RpcDriver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcDriverClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	DriverRpcTest(ctx context.Context, in *DriverRpcTestReq, opts ...grpc.CallOption) (*DriverRpcTestResp, error)
	Sms(ctx context.Context, in *SmsReq, opts ...grpc.CallOption) (*SmsResp, error)
	DriverReg(ctx context.Context, in *DriverRegReq, opts ...grpc.CallOption) (*DriverRegResp, error)
	DriverLogin(ctx context.Context, in *DriverLoginReq, opts ...grpc.CallOption) (*DriverLoginResp, error)
	RealName(ctx context.Context, in *RealNameReq, opts ...grpc.CallOption) (*RealNameResp, error)
	GetRealNameStatus(ctx context.Context, in *GetRealNameStatusReq, opts ...grpc.CallOption) (*GetRealNameStatusResp, error)
	Offline(ctx context.Context, in *DriverOfflineReq, opts ...grpc.CallOption) (*DriverOfflineResp, error)
	GetWalletBalance(ctx context.Context, in *GetWalletBalanceReq, opts ...grpc.CallOption) (*GetWalletBalanceResp, error)
	ListWalletLogs(ctx context.Context, in *ListWalletLogsReq, opts ...grpc.CallOption) (*ListWalletLogsResp, error)
	ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error)
	GetOrderRating(ctx context.Context, in *GetOrderRatingReq, opts ...grpc.CallOption) (*GetOrderRatingResp, error)
}

type rpcDriverClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcDriverClient(cc grpc.ClientConnInterface) RpcDriverClient {
	return &rpcDriverClient{cc}
}

func (c *rpcDriverClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RpcDriver_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) DriverRpcTest(ctx context.Context, in *DriverRpcTestReq, opts ...grpc.CallOption) (*DriverRpcTestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverRpcTestResp)
	err := c.cc.Invoke(ctx, RpcDriver_DriverRpcTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) Sms(ctx context.Context, in *SmsReq, opts ...grpc.CallOption) (*SmsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmsResp)
	err := c.cc.Invoke(ctx, RpcDriver_Sms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) DriverReg(ctx context.Context, in *DriverRegReq, opts ...grpc.CallOption) (*DriverRegResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverRegResp)
	err := c.cc.Invoke(ctx, RpcDriver_DriverReg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) DriverLogin(ctx context.Context, in *DriverLoginReq, opts ...grpc.CallOption) (*DriverLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverLoginResp)
	err := c.cc.Invoke(ctx, RpcDriver_DriverLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) RealName(ctx context.Context, in *RealNameReq, opts ...grpc.CallOption) (*RealNameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealNameResp)
	err := c.cc.Invoke(ctx, RpcDriver_RealName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) GetRealNameStatus(ctx context.Context, in *GetRealNameStatusReq, opts ...grpc.CallOption) (*GetRealNameStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRealNameStatusResp)
	err := c.cc.Invoke(ctx, RpcDriver_GetRealNameStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) Offline(ctx context.Context, in *DriverOfflineReq, opts ...grpc.CallOption) (*DriverOfflineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverOfflineResp)
	err := c.cc.Invoke(ctx, RpcDriver_Offline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) GetWalletBalance(ctx context.Context, in *GetWalletBalanceReq, opts ...grpc.CallOption) (*GetWalletBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletBalanceResp)
	err := c.cc.Invoke(ctx, RpcDriver_GetWalletBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) ListWalletLogs(ctx context.Context, in *ListWalletLogsReq, opts ...grpc.CallOption) (*ListWalletLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletLogsResp)
	err := c.cc.Invoke(ctx, RpcDriver_ListWalletLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResp)
	err := c.cc.Invoke(ctx, RpcDriver_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcDriverClient) GetOrderRating(ctx context.Context, in *GetOrderRatingReq, opts ...grpc.CallOption) (*GetOrderRatingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderRatingResp)
	err := c.cc.Invoke(ctx, RpcDriver_GetOrderRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcDriverServer is the server API for RpcDriver service.
// All implementations must embed UnimplementedRpcDriverServer
// for forward compatibility.
type RpcDriverServer interface {
	Ping(context.Context, *Request) (*Response, error)
	DriverRpcTest(context.Context, *DriverRpcTestReq) (*DriverRpcTestResp, error)
	Sms(context.Context, *SmsReq) (*SmsResp, error)
	DriverReg(context.Context, *DriverRegReq) (*DriverRegResp, error)
	DriverLogin(context.Context, *DriverLoginReq) (*DriverLoginResp, error)
	RealName(context.Context, *RealNameReq) (*RealNameResp, error)
	GetRealNameStatus(context.Context, *GetRealNameStatusReq) (*GetRealNameStatusResp, error)
	Offline(context.Context, *DriverOfflineReq) (*DriverOfflineResp, error)
	GetWalletBalance(context.Context, *GetWalletBalanceReq) (*GetWalletBalanceResp, error)
	ListWalletLogs(context.Context, *ListWalletLogsReq) (*ListWalletLogsResp, error)
	ListOrders(context.Context, *ListOrdersReq) (*ListOrdersResp, error)
	GetOrderRating(context.Context, *GetOrderRatingReq) (*GetOrderRatingResp, error)
	mustEmbedUnimplementedRpcDriverServer()
}

// UnimplementedRpcDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcDriverServer struct{}

func (UnimplementedRpcDriverServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcDriverServer) DriverRpcTest(context.Context, *DriverRpcTestReq) (*DriverRpcTestResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverRpcTest not implemented")
}
func (UnimplementedRpcDriverServer) Sms(context.Context, *SmsReq) (*SmsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Sms not implemented")
}
func (UnimplementedRpcDriverServer) DriverReg(context.Context, *DriverRegReq) (*DriverRegResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverReg not implemented")
}
func (UnimplementedRpcDriverServer) DriverLogin(context.Context, *DriverLoginReq) (*DriverLoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverLogin not implemented")
}
func (UnimplementedRpcDriverServer) RealName(context.Context, *RealNameReq) (*RealNameResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RealName not implemented")
}
func (UnimplementedRpcDriverServer) GetRealNameStatus(context.Context, *GetRealNameStatusReq) (*GetRealNameStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRealNameStatus not implemented")
}
func (UnimplementedRpcDriverServer) Offline(context.Context, *DriverOfflineReq) (*DriverOfflineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Offline not implemented")
}
func (UnimplementedRpcDriverServer) GetWalletBalance(context.Context, *GetWalletBalanceReq) (*GetWalletBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletBalance not implemented")
}
func (UnimplementedRpcDriverServer) ListWalletLogs(context.Context, *ListWalletLogsReq) (*ListWalletLogsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWalletLogs not implemented")
}
func (UnimplementedRpcDriverServer) ListOrders(context.Context, *ListOrdersReq) (*ListOrdersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedRpcDriverServer) GetOrderRating(context.Context, *GetOrderRatingReq) (*GetOrderRatingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderRating not implemented")
}
func (UnimplementedRpcDriverServer) mustEmbedUnimplementedRpcDriverServer() {}
func (UnimplementedRpcDriverServer) testEmbeddedByValue()                   {}

// UnsafeRpcDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcDriverServer will
// result in compilation errors.
type UnsafeRpcDriverServer interface {
	mustEmbedUnimplementedRpcDriverServer()
}

func RegisterRpcDriverServer(s grpc.ServiceRegistrar, srv RpcDriverServer) {
	// If the following call panics, it indicates UnimplementedRpcDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcDriver_ServiceDesc, srv)
}

func _RpcDriver_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_DriverRpcTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverRpcTestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).DriverRpcTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_DriverRpcTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).DriverRpcTest(ctx, req.(*DriverRpcTestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_Sms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).Sms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_Sms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).Sms(ctx, req.(*SmsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_DriverReg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverRegReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).DriverReg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_DriverReg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).DriverReg(ctx, req.(*DriverRegReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_DriverLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).DriverLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_DriverLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).DriverLogin(ctx, req.(*DriverLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_RealName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).RealName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_RealName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).RealName(ctx, req.(*RealNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_GetRealNameStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRealNameStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).GetRealNameStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_GetRealNameStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).GetRealNameStatus(ctx, req.(*GetRealNameStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_Offline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverOfflineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).Offline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_Offline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).Offline(ctx, req.(*DriverOfflineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_GetWalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).GetWalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_GetWalletBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).GetWalletBalance(ctx, req.(*GetWalletBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_ListWalletLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).ListWalletLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_ListWalletLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).ListWalletLogs(ctx, req.(*ListWalletLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).ListOrders(ctx, req.(*ListOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcDriver_GetOrderRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRatingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDriverServer).GetOrderRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDriver_GetOrderRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDriverServer).GetOrderRating(ctx, req.(*GetOrderRatingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcDriver_ServiceDesc is the grpc.ServiceDesc for RpcDriver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcDriver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcDriver.RpcDriver",
	HandlerType: (*RpcDriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RpcDriver_Ping_Handler,
		},
		{
			MethodName: "DriverRpcTest",
			Handler:    _RpcDriver_DriverRpcTest_Handler,
		},
		{
			MethodName: "Sms",
			Handler:    _RpcDriver_Sms_Handler,
		},
		{
			MethodName: "DriverReg",
			Handler:    _RpcDriver_DriverReg_Handler,
		},
		{
			MethodName: "DriverLogin",
			Handler:    _RpcDriver_DriverLogin_Handler,
		},
		{
			MethodName: "RealName",
			Handler:    _RpcDriver_RealName_Handler,
		},
		{
			MethodName: "GetRealNameStatus",
			Handler:    _RpcDriver_GetRealNameStatus_Handler,
		},
		{
			MethodName: "Offline",
			Handler:    _RpcDriver_Offline_Handler,
		},
		{
			MethodName: "GetWalletBalance",
			Handler:    _RpcDriver_GetWalletBalance_Handler,
		},
		{
			MethodName: "ListWalletLogs",
			Handler:    _RpcDriver_ListWalletLogs_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _RpcDriver_ListOrders_Handler,
		},
		{
			MethodName: "GetOrderRating",
			Handler:    _RpcDriver_GetOrderRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcDriver.proto",
}
