// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpcDriver.proto

package rpcDriver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_rpcDriver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_rpcDriver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type DriverRpcTestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRpcTestReq) Reset() {
	*x = DriverRpcTestReq{}
	mi := &file_rpcDriver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRpcTestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRpcTestReq) ProtoMessage() {}

func (x *DriverRpcTestReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRpcTestReq.ProtoReflect.Descriptor instead.
func (*DriverRpcTestReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{2}
}

func (x *DriverRpcTestReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DriverRpcTestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRpcTestResp) Reset() {
	*x = DriverRpcTestResp{}
	mi := &file_rpcDriver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRpcTestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRpcTestResp) ProtoMessage() {}

func (x *DriverRpcTestResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRpcTestResp.ProtoReflect.Descriptor instead.
func (*DriverRpcTestResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{3}
}

func (x *DriverRpcTestResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SmsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsReq) Reset() {
	*x = SmsReq{}
	mi := &file_rpcDriver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsReq) ProtoMessage() {}

func (x *SmsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsReq.ProtoReflect.Descriptor instead.
func (*SmsReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{4}
}

func (x *SmsReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SmsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsResp) Reset() {
	*x = SmsResp{}
	mi := &file_rpcDriver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsResp) ProtoMessage() {}

func (x *SmsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsResp.ProtoReflect.Descriptor instead.
func (*SmsResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{5}
}

func (x *SmsResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DriverRegReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRegReq) Reset() {
	*x = DriverRegReq{}
	mi := &file_rpcDriver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRegReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegReq) ProtoMessage() {}

func (x *DriverRegReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegReq.ProtoReflect.Descriptor instead.
func (*DriverRegReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{6}
}

func (x *DriverRegReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DriverRegReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DriverRegReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DriverRegResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRegResp) Reset() {
	*x = DriverRegResp{}
	mi := &file_rpcDriver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRegResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegResp) ProtoMessage() {}

func (x *DriverRegResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegResp.ProtoReflect.Descriptor instead.
func (*DriverRegResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{7}
}

func (x *DriverRegResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DriverLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Type          int64                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Lng           float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat           float64                `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLoginReq) Reset() {
	*x = DriverLoginReq{}
	mi := &file_rpcDriver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLoginReq) ProtoMessage() {}

func (x *DriverLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLoginReq.ProtoReflect.Descriptor instead.
func (*DriverLoginReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{8}
}

func (x *DriverLoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DriverLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DriverLoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DriverLoginReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DriverLoginReq) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *DriverLoginReq) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type DriverLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLoginResp) Reset() {
	*x = DriverLoginResp{}
	mi := &file_rpcDriver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLoginResp) ProtoMessage() {}

func (x *DriverLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLoginResp.ProtoReflect.Descriptor instead.
func (*DriverLoginResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{9}
}

func (x *DriverLoginResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverLoginResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RealNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CardNo        string                 `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CarNumber     string                 `protobuf:"bytes,5,opt,name=car_number,json=carNumber,proto3" json:"car_number,omitempty"`
	CarType       string                 `protobuf:"bytes,6,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	CarColor      string                 `protobuf:"bytes,7,opt,name=car_color,json=carColor,proto3" json:"car_color,omitempty"`
	LicensePhoto  string                 `protobuf:"bytes,8,opt,name=license_photo,json=licensePhoto,proto3" json:"license_photo,omitempty"`
	VehiclePhoto  string                 `protobuf:"bytes,9,opt,name=vehicle_photo,json=vehiclePhoto,proto3" json:"vehicle_photo,omitempty"`
	Email         string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameReq) Reset() {
	*x = RealNameReq{}
	mi := &file_rpcDriver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameReq) ProtoMessage() {}

func (x *RealNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameReq.ProtoReflect.Descriptor instead.
func (*RealNameReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{10}
}

func (x *RealNameReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RealNameReq) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *RealNameReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *RealNameReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RealNameReq) GetCarNumber() string {
	if x != nil {
		return x.CarNumber
	}
	return ""
}

func (x *RealNameReq) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *RealNameReq) GetCarColor() string {
	if x != nil {
		return x.CarColor
	}
	return ""
}

func (x *RealNameReq) GetLicensePhoto() string {
	if x != nil {
		return x.LicensePhoto
	}
	return ""
}

func (x *RealNameReq) GetVehiclePhoto() string {
	if x != nil {
		return x.VehiclePhoto
	}
	return ""
}

func (x *RealNameReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RealNameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameResp) Reset() {
	*x = RealNameResp{}
	mi := &file_rpcDriver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameResp) ProtoMessage() {}

func (x *RealNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameResp.ProtoReflect.Descriptor instead.
func (*RealNameResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{11}
}

func (x *RealNameResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetRealNameStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealNameStatusReq) Reset() {
	*x = GetRealNameStatusReq{}
	mi := &file_rpcDriver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealNameStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealNameStatusReq) ProtoMessage() {}

func (x *GetRealNameStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealNameStatusReq.ProtoReflect.Descriptor instead.
func (*GetRealNameStatusReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{12}
}

func (x *GetRealNameStatusReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type GetRealNameStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"` // 是否已资质认证成功
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`     // 1正常 2未实名 3禁用
	StatusName    string                 `protobuf:"bytes,3,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	RealName      string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"` // 脱敏姓名，未认证为空
	CarNumber     string                 `protobuf:"bytes,5,opt,name=car_number,json=carNumber,proto3" json:"car_number,omitempty"`
	CarType       string                 `protobuf:"bytes,6,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	CarColor      string                 `protobuf:"bytes,7,opt,name=car_color,json=carColor,proto3" json:"car_color,omitempty"`
	Avatar        string                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealNameStatusResp) Reset() {
	*x = GetRealNameStatusResp{}
	mi := &file_rpcDriver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealNameStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealNameStatusResp) ProtoMessage() {}

func (x *GetRealNameStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealNameStatusResp.ProtoReflect.Descriptor instead.
func (*GetRealNameStatusResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{13}
}

func (x *GetRealNameStatusResp) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *GetRealNameStatusResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRealNameStatusResp) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *GetRealNameStatusResp) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *GetRealNameStatusResp) GetCarNumber() string {
	if x != nil {
		return x.CarNumber
	}
	return ""
}

func (x *GetRealNameStatusResp) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *GetRealNameStatusResp) GetCarColor() string {
	if x != nil {
		return x.CarColor
	}
	return ""
}

func (x *GetRealNameStatusResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type DriverOfflineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverOfflineReq) Reset() {
	*x = DriverOfflineReq{}
	mi := &file_rpcDriver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverOfflineReq) ProtoMessage() {}

func (x *DriverOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverOfflineReq.ProtoReflect.Descriptor instead.
func (*DriverOfflineReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{14}
}

func (x *DriverOfflineReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type DriverOfflineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverOfflineResp) Reset() {
	*x = DriverOfflineResp{}
	mi := &file_rpcDriver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverOfflineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverOfflineResp) ProtoMessage() {}

func (x *DriverOfflineResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverOfflineResp.ProtoReflect.Descriptor instead.
func (*DriverOfflineResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{15}
}

func (x *DriverOfflineResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DriverOfflineResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetWalletBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceReq) Reset() {
	*x = GetWalletBalanceReq{}
	mi := &file_rpcDriver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceReq) ProtoMessage() {}

func (x *GetWalletBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceReq.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{16}
}

func (x *GetWalletBalanceReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type GetWalletBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceResp) Reset() {
	*x = GetWalletBalanceResp{}
	mi := &file_rpcDriver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceResp) ProtoMessage() {}

func (x *GetWalletBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceResp.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{17}
}

func (x *GetWalletBalanceResp) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ListWalletLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletLogsReq) Reset() {
	*x = ListWalletLogsReq{}
	mi := &file_rpcDriver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletLogsReq) ProtoMessage() {}

func (x *ListWalletLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletLogsReq.ProtoReflect.Descriptor instead.
func (*ListWalletLogsReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{18}
}

func (x *ListWalletLogsReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *ListWalletLogsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWalletLogsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWalletLogsReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type WalletLogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	SignedAmount  float64                `protobuf:"fixed64,4,opt,name=signed_amount,json=signedAmount,proto3" json:"signed_amount,omitempty"`
	Direction     string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	BalanceBefore float64                `protobuf:"fixed64,6,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"`
	BalanceAfter  float64                `protobuf:"fixed64,7,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Type          int32                  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	TypeName      string                 `protobuf:"bytes,9,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	StatusName    string                 `protobuf:"bytes,11,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	Remark        string                 `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletLogItem) Reset() {
	*x = WalletLogItem{}
	mi := &file_rpcDriver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletLogItem) ProtoMessage() {}

func (x *WalletLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletLogItem.ProtoReflect.Descriptor instead.
func (*WalletLogItem) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{19}
}

func (x *WalletLogItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WalletLogItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *WalletLogItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WalletLogItem) GetSignedAmount() float64 {
	if x != nil {
		return x.SignedAmount
	}
	return 0
}

func (x *WalletLogItem) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *WalletLogItem) GetBalanceBefore() float64 {
	if x != nil {
		return x.BalanceBefore
	}
	return 0
}

func (x *WalletLogItem) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *WalletLogItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WalletLogItem) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *WalletLogItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WalletLogItem) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *WalletLogItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *WalletLogItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListWalletLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*WalletLogItem       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletLogsResp) Reset() {
	*x = ListWalletLogsResp{}
	mi := &file_rpcDriver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletLogsResp) ProtoMessage() {}

func (x *ListWalletLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletLogsResp.ProtoReflect.Descriptor instead.
func (*ListWalletLogsResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{20}
}

func (x *ListWalletLogsResp) GetList() []*WalletLogItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListWalletLogsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWalletLogsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWalletLogsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 0全部 1待接单 2已接单 3已完成 4已取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReq) Reset() {
	*x = ListOrdersReq{}
	mi := &file_rpcDriver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReq) ProtoMessage() {}

func (x *ListOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReq.ProtoReflect.Descriptor instead.
func (*ListOrdersReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{21}
}

func (x *ListOrdersReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *ListOrdersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ListOrdersReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OrderListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartAddress  string                 `protobuf:"bytes,5,opt,name=start_address,json=startAddress,proto3" json:"start_address,omitempty"`
	EndAddress    string                 `protobuf:"bytes,6,opt,name=end_address,json=endAddress,proto3" json:"end_address,omitempty"`
	Distance      float64                `protobuf:"fixed64,7,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      int64                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Price         float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	PayType       int32                  `protobuf:"varint,10,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	StatusName    string                 `protobuf:"bytes,12,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	CancelReason  string                 `protobuf:"bytes,13,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	AcceptTime    string                 `protobuf:"bytes,14,opt,name=accept_time,json=acceptTime,proto3" json:"accept_time,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListItem) Reset() {
	*x = OrderListItem{}
	mi := &file_rpcDriver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListItem) ProtoMessage() {}

func (x *OrderListItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListItem.ProtoReflect.Descriptor instead.
func (*OrderListItem) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{22}
}

func (x *OrderListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderListItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderListItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderListItem) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *OrderListItem) GetStartAddress() string {
	if x != nil {
		return x.StartAddress
	}
	return ""
}

func (x *OrderListItem) GetEndAddress() string {
	if x != nil {
		return x.EndAddress
	}
	return ""
}

func (x *OrderListItem) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *OrderListItem) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *OrderListItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderListItem) GetPayType() int32 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *OrderListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderListItem) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *OrderListItem) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *OrderListItem) GetAcceptTime() string {
	if x != nil {
		return x.AcceptTime
	}
	return ""
}

func (x *OrderListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderListItem       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResp) Reset() {
	*x = ListOrdersResp{}
	mi := &file_rpcDriver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResp) ProtoMessage() {}

func (x *ListOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResp.ProtoReflect.Descriptor instead.
func (*ListOrdersResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{23}
}

func (x *ListOrdersResp) GetList() []*OrderListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListOrdersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetOrderRatingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRatingReq) Reset() {
	*x = GetOrderRatingReq{}
	mi := &file_rpcDriver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRatingReq) ProtoMessage() {}

func (x *GetOrderRatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRatingReq.ProtoReflect.Descriptor instead.
func (*GetOrderRatingReq) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{24}
}

func (x *GetOrderRatingReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *GetOrderRatingReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetOrderRatingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Rating        int64                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Tags          string                 `protobuf:"bytes,7,opt,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRatingResp) Reset() {
	*x = GetOrderRatingResp{}
	mi := &file_rpcDriver_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRatingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRatingResp) ProtoMessage() {}

func (x *GetOrderRatingResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcDriver_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRatingResp.ProtoReflect.Descriptor instead.
func (*GetOrderRatingResp) Descriptor() ([]byte, []int) {
	return file_rpcDriver_proto_rawDescGZIP(), []int{25}
}

func (x *GetOrderRatingResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderRatingResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrderRatingResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderRatingResp) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *GetOrderRatingResp) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetOrderRatingResp) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetOrderRatingResp) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GetOrderRatingResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_rpcDriver_proto protoreflect.FileDescriptor

const file_rpcDriver_proto_rawDesc = "" +
	"\n" +
	"\x0frpcDriver.proto\x12\trpcDriver\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"$\n" +
	"\x10DriverRpcTestReq\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"+\n" +
	"\x11DriverRpcTestResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x1e\n" +
	"\x06SmsReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"!\n" +
	"\aSmsResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"T\n" +
	"\fDriverRegReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"!\n" +
	"\rDriverRegResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x8e\x01\n" +
	"\x0eDriverLoginReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\x01R\x03lat\"3\n" +
	"\x0fDriverLoginResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xa4\x02\n" +
	"\vRealNameReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\acard_no\x18\x02 \x01(\tR\x06cardNo\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"car_number\x18\x05 \x01(\tR\tcarNumber\x12\x19\n" +
	"\bcar_type\x18\x06 \x01(\tR\acarType\x12\x1b\n" +
	"\tcar_color\x18\a \x01(\tR\bcarColor\x12#\n" +
	"\rlicense_photo\x18\b \x01(\tR\flicensePhoto\x12#\n" +
	"\rvehicle_photo\x18\t \x01(\tR\fvehiclePhoto\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\" \n" +
	"\fRealNameResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"3\n" +
	"\x14GetRealNameStatusReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\"\xf8\x01\n" +
	"\x15GetRealNameStatusResp\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\x03 \x01(\tR\n" +
	"statusName\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x1d\n" +
	"\n" +
	"car_number\x18\x05 \x01(\tR\tcarNumber\x12\x19\n" +
	"\bcar_type\x18\x06 \x01(\tR\acarType\x12\x1b\n" +
	"\tcar_color\x18\a \x01(\tR\bcarColor\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\".\n" +
	"\x10DriverOfflineReq\x12\x1a\n" +
	"\bdriverId\x18\x01 \x01(\x03R\bdriverId\"?\n" +
	"\x11DriverOfflineResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"2\n" +
	"\x13GetWalletBalanceReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\"0\n" +
	"\x14GetWalletBalanceResp\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\"|\n" +
	"\x11ListWalletLogsReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\"\x82\x03\n" +
	"\rWalletLogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12#\n" +
	"\rsigned_amount\x18\x04 \x01(\x01R\fsignedAmount\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x12%\n" +
	"\x0ebalance_before\x18\x06 \x01(\x01R\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\a \x01(\x01R\fbalanceAfter\x12\x12\n" +
	"\x04type\x18\b \x01(\x05R\x04type\x12\x1b\n" +
	"\ttype_name\x18\t \x01(\tR\btypeName\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\v \x01(\tR\n" +
	"statusName\x12\x16\n" +
	"\x06remark\x18\f \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\"\x89\x01\n" +
	"\x12ListWalletLogsResp\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.rpcDriver.WalletLogItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x90\x01\n" +
	"\rListOrdersReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\xbd\x03\n" +
	"\rOrderListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x03R\bdriverId\x12#\n" +
	"\rstart_address\x18\x05 \x01(\tR\fstartAddress\x12\x1f\n" +
	"\vend_address\x18\x06 \x01(\tR\n" +
	"endAddress\x12\x1a\n" +
	"\bdistance\x18\a \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\b \x01(\x03R\bduration\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12\x19\n" +
	"\bpay_type\x18\n" +
	" \x01(\x05R\apayType\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\f \x01(\tR\n" +
	"statusName\x12#\n" +
	"\rcancel_reason\x18\r \x01(\tR\fcancelReason\x12\x1f\n" +
	"\vaccept_time\x18\x0e \x01(\tR\n" +
	"acceptTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\"\x85\x01\n" +
	"\x0eListOrdersResp\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.rpcDriver.OrderListItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"K\n" +
	"\x11GetOrderRatingReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"\xda\x01\n" +
	"\x12GetOrderRatingResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x03R\bdriverId\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x03R\x06rating\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x12\n" +
	"\x04tags\x18\a \x01(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt2\xcd\x06\n" +
	"\tRpcDriver\x12/\n" +
	"\x04Ping\x12\x12.rpcDriver.Request\x1a\x13.rpcDriver.Response\x12J\n" +
	"\rDriverRpcTest\x12\x1b.rpcDriver.DriverRpcTestReq\x1a\x1c.rpcDriver.DriverRpcTestResp\x12,\n" +
	"\x03Sms\x12\x11.rpcDriver.SmsReq\x1a\x12.rpcDriver.SmsResp\x12>\n" +
	"\tDriverReg\x12\x17.rpcDriver.DriverRegReq\x1a\x18.rpcDriver.DriverRegResp\x12D\n" +
	"\vDriverLogin\x12\x19.rpcDriver.DriverLoginReq\x1a\x1a.rpcDriver.DriverLoginResp\x12;\n" +
	"\bRealName\x12\x16.rpcDriver.RealNameReq\x1a\x17.rpcDriver.RealNameResp\x12V\n" +
	"\x11GetRealNameStatus\x12\x1f.rpcDriver.GetRealNameStatusReq\x1a .rpcDriver.GetRealNameStatusResp\x12D\n" +
	"\aOffline\x12\x1b.rpcDriver.DriverOfflineReq\x1a\x1c.rpcDriver.DriverOfflineResp\x12S\n" +
	"\x10GetWalletBalance\x12\x1e.rpcDriver.GetWalletBalanceReq\x1a\x1f.rpcDriver.GetWalletBalanceResp\x12M\n" +
	"\x0eListWalletLogs\x12\x1c.rpcDriver.ListWalletLogsReq\x1a\x1d.rpcDriver.ListWalletLogsResp\x12A\n" +
	"\n" +
	"ListOrders\x12\x18.rpcDriver.ListOrdersReq\x1a\x19.rpcDriver.ListOrdersResp\x12M\n" +
	"\x0eGetOrderRating\x12\x1c.rpcDriver.GetOrderRatingReq\x1a\x1d.rpcDriver.GetOrderRatingRespB\rZ\v./rpcDriverb\x06proto3"

var (
	file_rpcDriver_proto_rawDescOnce sync.Once
	file_rpcDriver_proto_rawDescData []byte
)

func file_rpcDriver_proto_rawDescGZIP() []byte {
	file_rpcDriver_proto_rawDescOnce.Do(func() {
		file_rpcDriver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcDriver_proto_rawDesc), len(file_rpcDriver_proto_rawDesc)))
	})
	return file_rpcDriver_proto_rawDescData
}

var file_rpcDriver_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_rpcDriver_proto_goTypes = []any{
	(*Request)(nil),               // 0: rpcDriver.Request
	(*Response)(nil),              // 1: rpcDriver.Response
	(*DriverRpcTestReq)(nil),      // 2: rpcDriver.DriverRpcTestReq
	(*DriverRpcTestResp)(nil),     // 3: rpcDriver.DriverRpcTestResp
	(*SmsReq)(nil),                // 4: rpcDriver.SmsReq
	(*SmsResp)(nil),               // 5: rpcDriver.SmsResp
	(*DriverRegReq)(nil),          // 6: rpcDriver.DriverRegReq
	(*DriverRegResp)(nil),         // 7: rpcDriver.DriverRegResp
	(*DriverLoginReq)(nil),        // 8: rpcDriver.DriverLoginReq
	(*DriverLoginResp)(nil),       // 9: rpcDriver.DriverLoginResp
	(*RealNameReq)(nil),           // 10: rpcDriver.RealNameReq
	(*RealNameResp)(nil),          // 11: rpcDriver.RealNameResp
	(*GetRealNameStatusReq)(nil),  // 12: rpcDriver.GetRealNameStatusReq
	(*GetRealNameStatusResp)(nil), // 13: rpcDriver.GetRealNameStatusResp
	(*DriverOfflineReq)(nil),      // 14: rpcDriver.DriverOfflineReq
	(*DriverOfflineResp)(nil),     // 15: rpcDriver.DriverOfflineResp
	(*GetWalletBalanceReq)(nil),   // 16: rpcDriver.GetWalletBalanceReq
	(*GetWalletBalanceResp)(nil),  // 17: rpcDriver.GetWalletBalanceResp
	(*ListWalletLogsReq)(nil),     // 18: rpcDriver.ListWalletLogsReq
	(*WalletLogItem)(nil),         // 19: rpcDriver.WalletLogItem
	(*ListWalletLogsResp)(nil),    // 20: rpcDriver.ListWalletLogsResp
	(*ListOrdersReq)(nil),         // 21: rpcDriver.ListOrdersReq
	(*OrderListItem)(nil),         // 22: rpcDriver.OrderListItem
	(*ListOrdersResp)(nil),        // 23: rpcDriver.ListOrdersResp
	(*GetOrderRatingReq)(nil),     // 24: rpcDriver.GetOrderRatingReq
	(*GetOrderRatingResp)(nil),    // 25: rpcDriver.GetOrderRatingResp
}
var file_rpcDriver_proto_depIdxs = []int32{
	19, // 0: rpcDriver.ListWalletLogsResp.list:type_name -> rpcDriver.WalletLogItem
	22, // 1: rpcDriver.ListOrdersResp.list:type_name -> rpcDriver.OrderListItem
	0,  // 2: rpcDriver.RpcDriver.Ping:input_type -> rpcDriver.Request
	2,  // 3: rpcDriver.RpcDriver.DriverRpcTest:input_type -> rpcDriver.DriverRpcTestReq
	4,  // 4: rpcDriver.RpcDriver.Sms:input_type -> rpcDriver.SmsReq
	6,  // 5: rpcDriver.RpcDriver.DriverReg:input_type -> rpcDriver.DriverRegReq
	8,  // 6: rpcDriver.RpcDriver.DriverLogin:input_type -> rpcDriver.DriverLoginReq
	10, // 7: rpcDriver.RpcDriver.RealName:input_type -> rpcDriver.RealNameReq
	12, // 8: rpcDriver.RpcDriver.GetRealNameStatus:input_type -> rpcDriver.GetRealNameStatusReq
	14, // 9: rpcDriver.RpcDriver.Offline:input_type -> rpcDriver.DriverOfflineReq
	16, // 10: rpcDriver.RpcDriver.GetWalletBalance:input_type -> rpcDriver.GetWalletBalanceReq
	18, // 11: rpcDriver.RpcDriver.ListWalletLogs:input_type -> rpcDriver.ListWalletLogsReq
	21, // 12: rpcDriver.RpcDriver.ListOrders:input_type -> rpcDriver.ListOrdersReq
	24, // 13: rpcDriver.RpcDriver.GetOrderRating:input_type -> rpcDriver.GetOrderRatingReq
	1,  // 14: rpcDriver.RpcDriver.Ping:output_type -> rpcDriver.Response
	3,  // 15: rpcDriver.RpcDriver.DriverRpcTest:output_type -> rpcDriver.DriverRpcTestResp
	5,  // 16: rpcDriver.RpcDriver.Sms:output_type -> rpcDriver.SmsResp
	7,  // 17: rpcDriver.RpcDriver.DriverReg:output_type -> rpcDriver.DriverRegResp
	9,  // 18: rpcDriver.RpcDriver.DriverLogin:output_type -> rpcDriver.DriverLoginResp
	11, // 19: rpcDriver.RpcDriver.RealName:output_type -> rpcDriver.RealNameResp
	13, // 20: rpcDriver.RpcDriver.GetRealNameStatus:output_type -> rpcDriver.GetRealNameStatusResp
	15, // 21: rpcDriver.RpcDriver.Offline:output_type -> rpcDriver.DriverOfflineResp
	17, // 22: rpcDriver.RpcDriver.GetWalletBalance:output_type -> rpcDriver.GetWalletBalanceResp
	20, // 23: rpcDriver.RpcDriver.ListWalletLogs:output_type -> rpcDriver.ListWalletLogsResp
	23, // 24: rpcDriver.RpcDriver.ListOrders:output_type -> rpcDriver.ListOrdersResp
	25, // 25: rpcDriver.RpcDriver.GetOrderRating:output_type -> rpcDriver.GetOrderRatingResp
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpcDriver_proto_init() }
func file_rpcDriver_proto_init() {
	if File_rpcDriver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcDriver_proto_rawDesc), len(file_rpcDriver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcDriver_proto_goTypes,
		DependencyIndexes: file_rpcDriver_proto_depIdxs,
		MessageInfos:      file_rpcDriver_proto_msgTypes,
	}.Build()
	File_rpcDriver_proto = out.File
	file_rpcDriver_proto_goTypes = nil
	file_rpcDriver_proto_depIdxs = nil
}
