// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpcUser.proto

package server

import (
	"context"

	"rpcUser/internal/logic"
	"rpcUser/internal/svc"
	"rpcUser/rpcUser"
)

type RpcUserServer struct {
	svcCtx *svc.ServiceContext
	rpcUser.UnimplementedRpcUserServer
}

func NewRpcUserServer(svcCtx *svc.ServiceContext) *RpcUserServer {
	return &RpcUserServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcUserServer) Ping(ctx context.Context, in *rpcUser.Request) (*rpcUser.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *RpcUserServer) UserRpcTest(ctx context.Context, in *rpcUser.UserRpcTestReq) (*rpcUser.UserRpcTestResp, error) {
	l := logic.NewUserRpcTestLogic(ctx, s.svcCtx)
	return l.UserRpcTest(in)
}

func (s *RpcUserServer) Sms(ctx context.Context, in *rpcUser.SmsReq) (*rpcUser.SmsResp, error) {
	l := logic.NewSmsLogic(ctx, s.svcCtx)
	return l.Sms(in)
}

func (s *RpcUserServer) Register(ctx context.Context, in *rpcUser.RegisterReq) (*rpcUser.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *RpcUserServer) Login(ctx context.Context, in *rpcUser.LoginReq) (*rpcUser.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *RpcUserServer) RealName(ctx context.Context, in *rpcUser.RealNameReq) (*rpcUser.RealNameResp, error) {
	l := logic.NewRealNameLogic(ctx, s.svcCtx)
	return l.RealName(in)
}

func (s *RpcUserServer) GetRealNameStatus(ctx context.Context, in *rpcUser.GetRealNameStatusReq) (*rpcUser.GetRealNameStatusResp, error) {
	l := logic.NewGetRealNameStatusLogic(ctx, s.svcCtx)
	return l.GetRealNameStatus(in)
}

func (s *RpcUserServer) BalanceNotify(ctx context.Context, in *rpcUser.BalanceNotifyReq) (*rpcUser.BalanceNotifyResp, error) {
	l := logic.NewBalanceNotifyLogic(ctx, s.svcCtx)
	return l.BalanceNotify(in)
}

func (s *RpcUserServer) AliPayBalance(ctx context.Context, in *rpcUser.AliPayBalanceReq) (*rpcUser.AliPayBalanceResp, error) {
	l := logic.NewAliPayBalanceLogic(ctx, s.svcCtx)
	return l.AliPayBalance(in)
}

func (s *RpcUserServer) ListCoupons(ctx context.Context, in *rpcUser.ListCouponsReq) (*rpcUser.ListCouponsResp, error) {
	l := logic.NewListCouponsLogic(ctx, s.svcCtx)
	return l.ListCoupons(in)
}

func (s *RpcUserServer) RateOrder(ctx context.Context, in *rpcUser.RateOrderReq) (*rpcUser.RateOrderResp, error) {
	l := logic.NewRateOrderLogic(ctx, s.svcCtx)
	return l.RateOrder(in)
}

func (s *RpcUserServer) GetWalletBalance(ctx context.Context, in *rpcUser.GetWalletBalanceReq) (*rpcUser.GetWalletBalanceResp, error) {
	l := logic.NewGetWalletBalanceLogic(ctx, s.svcCtx)
	return l.GetWalletBalance(in)
}

func (s *RpcUserServer) ListWalletLogs(ctx context.Context, in *rpcUser.ListWalletLogsReq) (*rpcUser.ListWalletLogsResp, error) {
	l := logic.NewListWalletLogsLogic(ctx, s.svcCtx)
	return l.ListWalletLogs(in)
}

func (s *RpcUserServer) ListOrders(ctx context.Context, in *rpcUser.ListOrdersReq) (*rpcUser.ListOrdersResp, error) {
	l := logic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

func (s *RpcUserServer) GetOrderRating(ctx context.Context, in *rpcUser.GetOrderRatingReq) (*rpcUser.GetOrderRatingResp, error) {
	l := logic.NewGetOrderRatingLogic(ctx, s.svcCtx)
	return l.GetOrderRating(in)
}

func (s *RpcUserServer) DeleteOrderRating(ctx context.Context, in *rpcUser.DeleteOrderRatingReq) (*rpcUser.DeleteOrderRatingResp, error) {
	l := logic.NewDeleteOrderRatingLogic(ctx, s.svcCtx)
	return l.DeleteOrderRating(in)
}
